yarnPath: .yarn/releases/yarn-4.12.0.cjs

compressionLevel: 1

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmAuthToken: "${FA_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FA_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
