nodeLinker: node-modules

npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmAuthToken: "${FA_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FA_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
