/*
    Hugeicons Icon Component v. 0.0.4.b2
    By : [Donald Louch](https://donaldlouch.ca)

    Featuring : [Hugeicons : @hugeicons/react@1.0.8](https://hugeicons.com/icons)

    Here is an easy to use component that allows you to use the Hugeicons icon library in your React application. Currently I'm only importing the icons that I use for my personal website. More maybe added at a later time.

    To use this component, simply import it and pass in the name of the icon you want to use as a prop (type-safe). The name of the icon should be the same as the name of the icon in the [Hugeicons Library](https://hugeicons.com/icons).

    For example, if you want to use the "file-unknown"/"<FileUnknownIcon />" icons, you would pass in the name prop as "file-unknown". The component will then render the icon with the appropriate size and color.

    You can also pass in additional props to customize the appearance of the icon. For example:
        - color : The color of the icon. You can pass in any valid CSS color value or CSS variable.
        - size : The size of the icon. You can pass in any valid CSS size value.
        - variant : The variant of the icon. You can pass any variant style found on the [Hugeicons Library](https://hugeicons.com/icons).
        - weight : The thickness of the icon stroke. You can pass any thickness style found on the [Hugeicons Library](https://hugeicons.com/icons).

    Here is an example of how to use the component:

    import { HugeIcon } from "@/app/(Components)/HugeIcon"

    <HugeIcon name="file-unknown" color="red" size="2rem" />
    
    // For a alternate icon, you can pass in the name of the alternate icon as the altName prop, and the variant of the alternate icon as the altVariant prop. If you don't pass a altVariant it will default to original variant for the initial icon.
    <HugeIcon name="file-unknown" color="red" size="2rem" altStatus={FUNCTION}, altName="check-01", altVariant="twotone" />

    This will render the "file-unknown" icon with a red color and a size of 2rem.

    You can also use the component in a functional component or a class component. Here is an example of how to use it in a functional component:

    import { HugeIcon } from "@/app/(Components)/HugeIcon"

    const MyComponent = () => {
        return <HugeIcon name="file-unknown" color="red" size="2rem" />
    }
*/

import { HugeiconsIcon } from '@hugeicons/react'

import * as StrokeIcons from '@hugeicons-pro/core-stroke-rounded'
import * as SolidIcons from '@hugeicons-pro/core-solid-rounded'
import * as BulkIcons from '@hugeicons-pro/core-bulk-rounded'
import * as TwotoneIcons from '@hugeicons-pro/core-twotone-rounded'
import * as DuotoneIcons from '@hugeicons-pro/core-duotone-rounded'

export type iconVariant = "stroke" | "solid" | "bulk"  | "twotone" | "duotone"

export type IconName = "mouse-01" | "file-attachment" | "arrow-right-01" | "bluesky" | "youtube" | "video-01" | "video-02" | "mail-at-sign-01" | "arrow-all-direction" | "file-unknown" | "arrow-up-right-01" | "link-square-02" | "home-01" | "refresh" | "album-02" | "alert-diamond" | "camera-video" | "chatting-01" | "files-02" | "link-01" | "news" | "waving-hand-01" | "zap" | "cancel-01" | "cloud-upload" | "file-upload" | "calendar-03" | "delete-02" | "edit-02" | "image-02" | "image-upload-01" | "image-upload" | "information-circle" | "play" | "drag-drop" | "delete-03" | "delete-01" | "cloud-saving-done-01"| "plus-sign" | "pencil-edit-01" | "pencil-edit-02" | "grid" | "link-04" | "file-edit" | "alert-circle" | "checkmark-badge-03" | "cone-01" | "add-01" | "alert-01" | "alert-02" | "archive-02" | "bookmark-01" | "cancel-circle" | "checkmark-circle-02" | "dashboard-browsing" | "dashboard-speed-02" | "favourite" |"flag-02" | "folder-01" | "laurel-wreath" | "location-01" | "mail-01" | "notification-03" | "pencil" | "search-01" | "security-check" | "sent" | "settings-02" | "star" | "tag-01" | "save-money-dollar" | "seo" | "smart-phone-01" | "text-font" | "new-twitter" | "game-controller-01" | "wifi-connected-02" | "spotify" | "vimeo" | "music-note-square-02" | "shirt-01" | "soundcloud" | "icon-jar" | "facebook-02" | "github" | "instagram" | "laptop-check" | "linkedin-02" | "threads" | "tiktok" | "property-edit" | "view" | "arrow-left-02" | "arrow-left-03" |"arrow-right-02" | "arrow-right-03" | "go-backward-10-sec" | "go-forward-10-sec" | "pause" | "loading-03" | "arrow-down-01" | "briefcase-02" | "dashboard-square-02" | "job-search" | "passport-01" | "passport" | "hand-pointing-right-01" | "quote-down" | "login-01" | "twitter" | "files-01" | "tick-01" | "ticket-01" | "remove-01" |"book-02" | "contact" | "time-02" | "license" | "task-add-01" | "task-done-01" | "task-edit-01" | "arrow-down-02" | "checkmark-badge-01" | "menu-01" | "remove-02" | "unavailable" | "task-01" | "user" | "user-shield-01" | "album-01" | "desk" | "globe-02" | "pin-location-03" | "tags" | "database-02" | "library" | "user-multiple-02" | "arrow-expand-01" | "arrow-expand" | "arrow-horizontal" | "arrow-left-01" | "arrow-shrink-01" | "arrow-shrink" | "arrow-up-right-02" | "copy-01" | "database-01" | "liver" | "maximize-screen" | "minimize-screen" | "share-05" | "volume-mute-01" | "volume-off" | "maps-search" | "camera-01" | "filter" | "pin" | "sorting-19" | "sorting-91" | "music-note-01" | "delete-04" | "apple" | "github-01" | "message-download-01" | "clipboard" | "inbox" | "document-validation" | "loading-02" | "traffic-light" | "arrow-up-02" | "left-to-right-block-quote" | "mail-edit-01" | "check-list" | "arrow-down-right-01" | "more-horizontal" | "logout-01"

export type IconArray = {name : IconName, variant? : iconVariant}

export default function HugeIcon({ name, variant, size, color, weight, clickOption, altStatus, altName, altVariant } : { name : IconName, variant? : iconVariant, size? : any, color? : string, weight? : any, [key : string] : any, clickOption? : any, altStatus? : boolean, altIcon? : IconName, altVariant? : iconVariant }) {
    const options = { size : size ? size  : undefined, color : color ? color  : "currentColor", strokeWidth : weight ? weight  : undefined}
    
    const iconName = altStatus && altName ? altName  : name
    const iconVariant = altStatus && altVariant ? altVariant  : variant ? variant  : "stroke"

    const getIcon : any = 
       iconName === "mouse-01" && iconVariant === "stroke" ? StrokeIcons.Mouse01StrokeRounded
            : iconName === "mouse-01" && iconVariant === "solid" ? SolidIcons.Mouse01SolidRounded 
            : iconName === "mouse-01" && iconVariant === "bulk" ? BulkIcons.Mouse01BulkRounded 
            : iconName === "mouse-01" && iconVariant === "twotone" ? TwotoneIcons.Mouse01TwotoneRounded
            : iconName === "mouse-01" && iconVariant === "duotone" ? DuotoneIcons.Mouse01DuotoneRounded
        : iconName === "file-unknown" && iconVariant === "stroke" ? StrokeIcons.FileUnknownStrokeRounded
            : iconName === "file-unknown" && iconVariant === "solid" ? SolidIcons.FileUnknownSolidRounded 
            : iconName === "file-unknown" && iconVariant === "bulk" ? BulkIcons.FileUnknownBulkRounded 
            : iconName === "file-unknown" && iconVariant === "twotone" ? TwotoneIcons.FileUnknownTwotoneRounded
            : iconName === "file-unknown" && iconVariant === "duotone" ? DuotoneIcons.FileUnknownDuotoneRounded 
        : iconName === "bluesky" && iconVariant === "stroke" ?  StrokeIcons.BlueskyStrokeRounded
            : iconName === "bluesky" && iconVariant === "solid" ? SolidIcons.BlueskySolidRounded 
            : iconName === "bluesky" && iconVariant === "bulk" ? BulkIcons.BlueskyBulkRounded 
            : iconName === "bluesky" && iconVariant === "twotone" ? TwotoneIcons.BlueskyTwotoneRounded
            : iconName === "bluesky" && iconVariant === "duotone" ? DuotoneIcons.BlueskyDuotoneRounded
        : iconName === "mouse-01" && iconVariant === "stroke" ? StrokeIcons.Mouse01StrokeRounded 
            : iconName === "mouse-01" && iconVariant === "solid" ? SolidIcons.Mouse01SolidRounded 
            : iconName === "mouse-01" && iconVariant === "bulk" ? BulkIcons.Mouse01BulkRounded 
            : iconName === "mouse-01" && iconVariant === "twotone" ? TwotoneIcons.Mouse01TwotoneRounded
            : iconName === "mouse-01" && iconVariant === "duotone" ? DuotoneIcons.Mouse01DuotoneRounded
        : iconName === "file-attachment" && iconVariant === "stroke" ? StrokeIcons.FileAttachmentStrokeRounded 
            : iconName === "file-attachment" && iconVariant === "solid" ? SolidIcons.FileAttachmentSolidRounded 
            : iconName === "file-attachment" && iconVariant === "bulk" ? BulkIcons.FileAttachmentBulkRounded 
            : iconName === "file-attachment" && iconVariant === "twotone" ? TwotoneIcons.FileAttachmentTwotoneRounded
            : iconName === "file-attachment" && iconVariant === "duotone" ? DuotoneIcons.FileAttachmentDuotoneRounded
        : iconName === "logout-01" && iconVariant === "stroke" ? StrokeIcons.Logout01StrokeRounded 
            : iconName === "logout-01" && iconVariant === "solid" ? SolidIcons.Logout01SolidRounded 
            : iconName === "logout-01" && iconVariant === "bulk" ? BulkIcons.Logout01BulkRounded 
            : iconName === "logout-01" && iconVariant === "twotone" ? TwotoneIcons.Logout01TwotoneRounded
            : iconName === "logout-01" && iconVariant === "duotone" ? DuotoneIcons.Logout01DuotoneRounded
        : iconName === "more-horizontal" && iconVariant === "stroke" ? StrokeIcons.MoreHorizontalStrokeRounded 
            : iconName === "more-horizontal" && iconVariant === "solid" ? SolidIcons.MoreHorizontalSolidRounded 
            : iconName === "more-horizontal" && iconVariant === "bulk" ? BulkIcons.MoreHorizontalBulkRounded 
            : iconName === "more-horizontal" && iconVariant === "twotone" ? TwotoneIcons.MoreHorizontalTwotoneRounded
            : iconName === "more-horizontal" && iconVariant === "duotone" ? DuotoneIcons.MoreHorizontalDuotoneRounded
        : iconName === "check-list" && iconVariant === "stroke" ? StrokeIcons.CheckListStrokeRounded 
            : iconName === "check-list" && iconVariant === "solid" ? SolidIcons.CheckListSolidRounded 
            : iconName === "check-list" && iconVariant === "bulk" ? BulkIcons.CheckListBulkRounded 
            : iconName === "check-list" && iconVariant === "twotone" ? TwotoneIcons.CheckListTwotoneRounded
            : iconName === "check-list" && iconVariant === "duotone" ? DuotoneIcons.CheckListDuotoneRounded
        : iconName === "arrow-down-right-01" && iconVariant === "stroke" ? StrokeIcons.ArrowDownRight01StrokeRounded 
            : iconName === "arrow-down-right-01" && iconVariant === "solid" ? SolidIcons.ArrowDownRight01SolidRounded 
            : iconName === "arrow-down-right-01" && iconVariant === "bulk" ? BulkIcons.ArrowDownRight01BulkRounded 
            : iconName === "arrow-down-right-01" && iconVariant === "twotone" ? TwotoneIcons.ArrowDownRight01TwotoneRounded
            : iconName === "arrow-down-right-01" && iconVariant === "duotone" ? DuotoneIcons.ArrowDownRight01DuotoneRounded
        : iconName === "left-to-right-block-quote" && iconVariant === "stroke" ? StrokeIcons.LeftToRightBlockQuoteStrokeRounded 
            : iconName === "left-to-right-block-quote" && iconVariant === "solid" ? SolidIcons.LeftToRightBlockQuoteSolidRounded 
            : iconName === "left-to-right-block-quote" && iconVariant === "bulk" ? BulkIcons.LeftToRightBlockQuoteBulkRounded 
            : iconName === "left-to-right-block-quote" && iconVariant === "twotone" ? TwotoneIcons.LeftToRightBlockQuoteTwotoneRounded
            : iconName === "left-to-right-block-quote" && iconVariant === "duotone" ? DuotoneIcons.LeftToRightBlockQuoteDuotoneRounded
        : iconName === "youtube" && iconVariant === "stroke" ? StrokeIcons.YoutubeStrokeRounded 
            : iconName === "youtube" && iconVariant === "solid" ? SolidIcons.YoutubeSolidRounded 
            : iconName === "youtube" && iconVariant === "bulk" ? BulkIcons.YoutubeBulkRounded 
            : iconName === "youtube" && iconVariant === "twotone" ? TwotoneIcons.YoutubeTwotoneRounded
            : iconName === "youtube" && iconVariant === "duotone" ? DuotoneIcons.YoutubeDuotoneRounded 
        : iconName === "mail-edit-01" && iconVariant === "stroke" ? StrokeIcons.MailEdit01StrokeRounded 
            : iconName === "mail-edit-01" && iconVariant === "solid" ? SolidIcons.MailEdit01SolidRounded 
            : iconName === "mail-edit-01" && iconVariant === "bulk" ? BulkIcons.MailEdit01BulkRounded 
            : iconName === "mail-edit-01" && iconVariant === "twotone" ? TwotoneIcons.MailEdit01TwotoneRounded
            : iconName === "mail-edit-01" && iconVariant === "duotone" ? DuotoneIcons.MailEdit01DuotoneRounded 
        : iconName === "video-01" && iconVariant === "stroke" ? StrokeIcons.Video01StrokeRounded 
            : iconName === "video-01" && iconVariant === "solid" ? SolidIcons.Video01SolidRounded 
            : iconName === "video-01" && iconVariant === "bulk" ? BulkIcons.Video01BulkRounded 
            : iconName === "video-01" && iconVariant === "twotone" ? TwotoneIcons.Video01TwotoneRounded
            : iconName === "video-01" && iconVariant === "duotone" ? DuotoneIcons.Video01DuotoneRounded 
        : iconName === "video-02" && iconVariant === "stroke" ? StrokeIcons.Video02StrokeRounded 
            : iconName === "video-02" && iconVariant === "solid" ? SolidIcons.Video02SolidRounded 
            : iconName === "video-02" && iconVariant === "bulk" ? BulkIcons.Video02BulkRounded 
            : iconName === "video-02" && iconVariant === "twotone" ? TwotoneIcons.Video02TwotoneRounded                
            : iconName === "video-02" && iconVariant === "duotone" ? DuotoneIcons.Video02DuotoneRounded 
        : iconName === "mail-at-sign-01" && iconVariant === "stroke" ? StrokeIcons.MailAtSign01StrokeRounded 
            : iconName === "mail-at-sign-01" && iconVariant === "solid" ? SolidIcons.MailAtSign01SolidRounded 
            : iconName === "mail-at-sign-01" && iconVariant === "bulk" ? BulkIcons.MailAtSign01BulkRounded 
            : iconName === "mail-at-sign-01" && iconVariant === "twotone" ? TwotoneIcons.MailAtSign01TwotoneRounded                
            : iconName === "mail-at-sign-01" && iconVariant === "duotone" ? DuotoneIcons.MailAtSign01DuotoneRounded 
        : iconName === "arrow-all-direction" && iconVariant === "stroke" ? StrokeIcons.ArrowAllDirectionStrokeRounded 
            : iconName === "arrow-all-direction" && iconVariant === "solid" ? SolidIcons.ArrowAllDirectionSolidRounded 
            : iconName === "arrow-all-direction" && iconVariant === "bulk" ? BulkIcons.ArrowAllDirectionBulkRounded 
            : iconName === "arrow-all-direction" && iconVariant === "twotone" ? TwotoneIcons.ArrowAllDirectionTwotoneRounded                
            : iconName === "arrow-all-direction" && iconVariant === "duotone" ? DuotoneIcons.ArrowAllDirectionDuotoneRounded
        : iconName === "arrow-up-right-01" && iconVariant === "stroke" ? StrokeIcons.ArrowUpRight01StrokeRounded
            : iconName === "arrow-up-right-01" && iconVariant === "solid" ? SolidIcons.ArrowUpRight01SolidRounded
            : iconName === "arrow-up-right-01" && iconVariant === "bulk" ? BulkIcons.ArrowUpRight01BulkRounded
            : iconName === "arrow-up-right-01" && iconVariant === "twotone" ? TwotoneIcons.ArrowUpRight01TwotoneRounded
            : iconName === "arrow-up-right-01" && iconVariant === "duotone" ? DuotoneIcons.ArrowUpRight01DuotoneRounded
        : iconName === "link-square-02" && iconVariant === "stroke" ? StrokeIcons.LinkSquare02StrokeRounded
            : iconName === "link-square-02" && iconVariant === "solid" ? SolidIcons.LinkSquare02SolidRounded
            : iconName === "link-square-02" && iconVariant === "bulk" ? BulkIcons.LinkSquare02BulkRounded
            : iconName === "link-square-02" && iconVariant === "twotone" ? TwotoneIcons.LinkSquare02TwotoneRounded
            : iconName === "link-square-02" && iconVariant === "duotone" ? DuotoneIcons.LinkSquare02DuotoneRounded
        : iconName === "home-01" && iconVariant === "stroke" ? StrokeIcons.Home01StrokeRounded
            : iconName === "home-01" && iconVariant === "solid" ? SolidIcons.Home01SolidRounded
            : iconName === "home-01" && iconVariant === "bulk" ? BulkIcons.Home01BulkRounded
            : iconName === "home-01" && iconVariant === "twotone" ? TwotoneIcons.Home01TwotoneRounded
            : iconName === "home-01" && iconVariant === "duotone" ? DuotoneIcons.Home01DuotoneRounded
        : iconName === "refresh" && iconVariant === "stroke" ? StrokeIcons.RefreshStrokeRounded
            : iconName === "refresh" && iconVariant === "solid" ? SolidIcons.RefreshSolidRounded
            : iconName === "refresh" && iconVariant === "bulk" ? BulkIcons.RefreshBulkRounded
            : iconName === "refresh" && iconVariant === "twotone" ? TwotoneIcons.RefreshTwotoneRounded
            : iconName === "refresh" && iconVariant === "duotone" ? DuotoneIcons.RefreshDuotoneRounded
        : iconName === "album-02" && iconVariant === "stroke" ? StrokeIcons.Album02StrokeRounded
            : iconName === "album-02" && iconVariant === "solid" ? SolidIcons.Album02SolidRounded
            : iconName === "album-02" && iconVariant === "bulk" ? BulkIcons.Album02BulkRounded
            : iconName === "album-02" && iconVariant === "twotone" ? TwotoneIcons.Album02TwotoneRounded
            : iconName === "album-02" && iconVariant === "duotone" ? DuotoneIcons.Album02DuotoneRounded
        : iconName === "alert-diamond" && iconVariant === "stroke" ? StrokeIcons.AlertDiamondStrokeRounded
            : iconName === "alert-diamond" && iconVariant === "solid" ? SolidIcons.AlertDiamondSolidRounded
            : iconName === "alert-diamond" && iconVariant === "bulk" ? BulkIcons.AlertDiamondBulkRounded
            : iconName === "alert-diamond" && iconVariant === "twotone" ? TwotoneIcons.AlertDiamondTwotoneRounded
            : iconName === "alert-diamond" && iconVariant === "duotone" ? DuotoneIcons.AlertDiamondDuotoneRounded
        : iconName === "camera-video" && iconVariant === "stroke" ? StrokeIcons.CameraVideoStrokeRounded
            : iconName === "camera-video" && iconVariant === "solid" ? SolidIcons.CameraVideoSolidRounded
            : iconName === "camera-video" && iconVariant === "bulk" ? BulkIcons.CameraVideoBulkRounded
            : iconName === "camera-video" && iconVariant === "twotone" ? TwotoneIcons.CameraVideoTwotoneRounded
            : iconName === "camera-video" && iconVariant === "duotone" ? DuotoneIcons.CameraVideoDuotoneRounded
        : iconName === "chatting-01" && iconVariant === "stroke" ? StrokeIcons.Chatting01StrokeRounded
            : iconName === "chatting-01" && iconVariant === "solid" ? SolidIcons.Chatting01SolidRounded
            : iconName === "chatting-01" && iconVariant === "bulk" ? BulkIcons.Chatting01BulkRounded
            : iconName === "chatting-01" && iconVariant === "twotone" ? TwotoneIcons.Chatting01TwotoneRounded
            : iconName === "chatting-01" && iconVariant === "duotone" ? DuotoneIcons.Chatting01DuotoneRounded
        : iconName === "files-02" && iconVariant === "stroke" ? StrokeIcons.Files02StrokeRounded
            : iconName === "files-02" && iconVariant === "solid" ? SolidIcons.Files02SolidRounded
            : iconName === "files-02" && iconVariant === "bulk" ? BulkIcons.Files02BulkRounded
            : iconName === "files-02" && iconVariant === "twotone" ? TwotoneIcons.Files02TwotoneRounded
            : iconName === "files-02" && iconVariant === "duotone" ? DuotoneIcons.Files02DuotoneRounded
        : iconName === "link-01" && iconVariant === "stroke" ? StrokeIcons.Link01StrokeRounded
            : iconName === "link-01" && iconVariant === "solid" ? SolidIcons.Link01SolidRounded
            : iconName === "link-01" && iconVariant === "bulk" ? BulkIcons.Link01BulkRounded
            : iconName === "link-01" && iconVariant === "twotone" ? TwotoneIcons.Link01TwotoneRounded
            : iconName === "link-01" && iconVariant === "duotone" ? DuotoneIcons.Link01DuotoneRounded
        : iconName === "news" && iconVariant === "stroke" ? StrokeIcons.NewsStrokeRounded
            : iconName === "news" && iconVariant === "solid" ? SolidIcons.NewsSolidRounded
            : iconName === "news" && iconVariant === "bulk" ? BulkIcons.NewsBulkRounded
            : iconName === "news" && iconVariant === "twotone" ? TwotoneIcons.NewsTwotoneRounded
            : iconName === "news" && iconVariant === "duotone" ? DuotoneIcons.NewsDuotoneRounded
        : iconName === "waving-hand-01" && iconVariant === "stroke" ? StrokeIcons.WavingHand01StrokeRounded
            : iconName === "waving-hand-01" && iconVariant === "solid" ? SolidIcons.WavingHand01SolidRounded
            : iconName === "waving-hand-01" && iconVariant === "bulk" ? BulkIcons.WavingHand01BulkRounded
            : iconName === "waving-hand-01" && iconVariant === "twotone" ? TwotoneIcons.WavingHand01TwotoneRounded
            : iconName === "waving-hand-01" && iconVariant === "duotone" ? DuotoneIcons.WavingHand01DuotoneRounded
        : iconName === "zap" && iconVariant === "stroke" ? StrokeIcons.ZapStrokeRounded
            : iconName === "zap" && iconVariant === "solid" ? SolidIcons.ZapSolidRounded
            : iconName === "zap" && iconVariant === "bulk" ? BulkIcons.ZapBulkRounded
            : iconName === "zap" && iconVariant === "twotone" ? TwotoneIcons.ZapTwotoneRounded
            : iconName === "zap" && iconVariant === "duotone" ? DuotoneIcons.ZapDuotoneRounded
        : iconName === "cancel-01" && iconVariant === "stroke" ? StrokeIcons.Cancel01StrokeRounded
            : iconName === "cancel-01" && iconVariant === "solid" ? SolidIcons.Cancel01SolidRounded
            : iconName === "cancel-01" && iconVariant === "bulk" ? BulkIcons.Cancel01BulkRounded
            : iconName === "cancel-01" && iconVariant === "twotone" ? TwotoneIcons.Cancel01TwotoneRounded
            : iconName === "cancel-01" && iconVariant === "duotone" ? DuotoneIcons.Cancel01DuotoneRounded
        : iconName === "cloud-upload" && iconVariant === "stroke" ? StrokeIcons.CloudUploadStrokeRounded
            : iconName === "cloud-upload" && iconVariant === "solid" ? SolidIcons.CloudUploadSolidRounded
            : iconName === "cloud-upload" && iconVariant === "bulk" ? BulkIcons.CloudUploadBulkRounded
            : iconName === "cloud-upload" && iconVariant === "twotone" ? TwotoneIcons.CloudUploadTwotoneRounded
            : iconName === "cloud-upload" && iconVariant === "duotone" ? DuotoneIcons.CloudUploadDuotoneRounded
        : iconName === "file-upload" && iconVariant === "stroke" ? StrokeIcons.FileUploadStrokeRounded
            : iconName === "file-upload" && iconVariant === "solid" ? SolidIcons.FileUploadSolidRounded
            : iconName === "file-upload" && iconVariant === "bulk" ? BulkIcons.FileUploadBulkRounded
            : iconName === "file-upload" && iconVariant === "twotone" ? TwotoneIcons.FileUploadTwotoneRounded
            : iconName === "file-upload" && iconVariant === "duotone" ? DuotoneIcons.FileUploadDuotoneRounded
        : iconName === "calendar-03" && iconVariant === "stroke" ? StrokeIcons.Calendar03StrokeRounded
            : iconName === "calendar-03" && iconVariant === "solid" ? SolidIcons.Calendar03SolidRounded
            : iconName === "calendar-03" && iconVariant === "bulk" ? BulkIcons.Calendar03BulkRounded
            : iconName === "calendar-03" && iconVariant === "twotone" ? TwotoneIcons.Calendar03TwotoneRounded
            : iconName === "calendar-03" && iconVariant === "duotone" ? DuotoneIcons.Calendar03DuotoneRounded
        : iconName === "delete-02" && iconVariant === "stroke" ? StrokeIcons.Delete02StrokeRounded
            : iconName === "delete-02" && iconVariant === "solid" ? SolidIcons.Delete02SolidRounded
            : iconName === "delete-02" && iconVariant === "bulk" ? BulkIcons.Delete02BulkRounded
            : iconName === "delete-02" && iconVariant === "twotone" ? TwotoneIcons.Delete02TwotoneRounded
            : iconName === "delete-02" && iconVariant === "duotone" ? DuotoneIcons.Delete02DuotoneRounded
        : iconName === "edit-02" && iconVariant === "stroke" ? StrokeIcons.Edit02StrokeRounded
            : iconName === "edit-02" && iconVariant === "solid" ? SolidIcons.Edit02SolidRounded
            : iconName === "edit-02" && iconVariant === "bulk" ? BulkIcons.Edit02BulkRounded
            : iconName === "edit-02" && iconVariant === "twotone" ? TwotoneIcons.Edit02TwotoneRounded
            : iconName === "edit-02" && iconVariant === "duotone" ? DuotoneIcons.Edit02DuotoneRounded
        : iconName === "image-02" && iconVariant === "stroke" ? StrokeIcons.Image02StrokeRounded
            : iconName === "image-02" && iconVariant === "solid" ? SolidIcons.Image02SolidRounded
            : iconName === "image-02" && iconVariant === "bulk" ? BulkIcons.Image02BulkRounded
            : iconName === "image-02" && iconVariant === "twotone" ? TwotoneIcons.Image02TwotoneRounded
            : iconName === "image-02" && iconVariant === "duotone" ? DuotoneIcons.Image02DuotoneRounded
        : iconName === "image-upload-01" && iconVariant === "stroke" ? StrokeIcons.ImageUpload01StrokeRounded
            : iconName === "image-upload-01" && iconVariant === "solid" ? SolidIcons.ImageUpload01SolidRounded
            : iconName === "image-upload-01" && iconVariant === "bulk" ? BulkIcons.ImageUpload01BulkRounded
            : iconName === "image-upload-01" && iconVariant === "twotone" ? TwotoneIcons.ImageUpload01TwotoneRounded
            : iconName === "image-upload-01" && iconVariant === "duotone" ? DuotoneIcons.ImageUpload01DuotoneRounded
        : iconName === "image-upload" && iconVariant === "stroke" ? StrokeIcons.ImageUploadStrokeRounded
            : iconName === "image-upload" && iconVariant === "solid" ? SolidIcons.ImageUploadSolidRounded
            : iconName === "image-upload" && iconVariant === "bulk" ? BulkIcons.ImageUploadBulkRounded
            : iconName === "image-upload" && iconVariant === "twotone" ? TwotoneIcons.ImageUploadTwotoneRounded
            : iconName === "image-upload" && iconVariant === "duotone" ? DuotoneIcons.ImageUploadDuotoneRounded
        : iconName === "information-circle" && iconVariant === "stroke" ? StrokeIcons.InformationCircleStrokeRounded
            : iconName === "information-circle" && iconVariant === "solid" ? SolidIcons.InformationCircleSolidRounded
            : iconName === "information-circle" && iconVariant === "bulk" ? BulkIcons.InformationCircleBulkRounded
            : iconName === "information-circle" && iconVariant === "twotone" ? TwotoneIcons.InformationCircleTwotoneRounded
            : iconName === "information-circle" && iconVariant === "duotone" ? DuotoneIcons.InformationCircleDuotoneRounded
        : iconName === "play" && iconVariant === "stroke" ? StrokeIcons.PlayStrokeRounded
            : iconName === "play" && iconVariant === "solid" ? SolidIcons.PlaySolidRounded
            : iconName === "play" && iconVariant === "bulk" ? BulkIcons.PlayBulkRounded
            : iconName === "play" && iconVariant === "twotone" ? TwotoneIcons.PlayTwotoneRounded
            : iconName === "play" && iconVariant === "duotone" ? DuotoneIcons.PlayDuotoneRounded
        : iconName === "drag-drop" && iconVariant === "stroke" ? StrokeIcons.DragDropStrokeRounded
            : iconName === "drag-drop" && iconVariant === "solid" ? SolidIcons.DragDropSolidRounded
            : iconName === "drag-drop" && iconVariant === "bulk" ? BulkIcons.DragDropBulkRounded
            : iconName === "drag-drop" && iconVariant === "twotone" ? TwotoneIcons.DragDropTwotoneRounded
            : iconName === "drag-drop" && iconVariant === "duotone" ? DuotoneIcons.DragDropDuotoneRounded
        : iconName === "delete-03" && iconVariant === "stroke" ? StrokeIcons.Delete03StrokeRounded
            : iconName === "delete-03" && iconVariant === "solid" ? SolidIcons.Delete03SolidRounded
            : iconName === "delete-03" && iconVariant === "bulk" ? BulkIcons.Delete03BulkRounded
            : iconName === "delete-03" && iconVariant === "twotone" ? TwotoneIcons.Delete03TwotoneRounded
            : iconName === "delete-03" && iconVariant === "duotone" ? DuotoneIcons.Delete03DuotoneRounded
        : iconName === "delete-01" && iconVariant === "stroke" ? StrokeIcons.Delete01StrokeRounded
            : iconName === "delete-01" && iconVariant === "solid" ? SolidIcons.Delete01SolidRounded
            : iconName === "delete-01" && iconVariant === "bulk" ? BulkIcons.Delete01BulkRounded
            : iconName === "delete-01" && iconVariant === "twotone" ? TwotoneIcons.Delete01TwotoneRounded
            : iconName === "delete-01" && iconVariant === "duotone" ? DuotoneIcons.Delete01DuotoneRounded
        : iconName === "cloud-saving-done-01" && iconVariant === "stroke" ? StrokeIcons.CloudSavingDone01StrokeRounded
            : iconName === "cloud-saving-done-01" && iconVariant === "solid" ? SolidIcons.CloudSavingDone01SolidRounded
            : iconName === "cloud-saving-done-01" && iconVariant === "bulk" ? BulkIcons.CloudSavingDone01BulkRounded
            : iconName === "cloud-saving-done-01" && iconVariant === "twotone" ? TwotoneIcons.CloudSavingDone01TwotoneRounded
            : iconName === "cloud-saving-done-01" && iconVariant === "duotone" ? DuotoneIcons.CloudSavingDone01DuotoneRounded
        : iconName === "plus-sign" && iconVariant === "stroke" ? StrokeIcons.PlusSignStrokeRounded
            : iconName === "plus-sign" && iconVariant === "solid" ? SolidIcons.PlusSignSolidRounded
            : iconName === "plus-sign" && iconVariant === "bulk" ? BulkIcons.PlusSignBulkRounded
            : iconName === "plus-sign" && iconVariant === "twotone" ? TwotoneIcons.PlusSignTwotoneRounded
            : iconName === "plus-sign" && iconVariant === "duotone" ? DuotoneIcons.PlusSignDuotoneRounded
        : iconName === "pencil-edit-01" && iconVariant === "stroke" ? StrokeIcons.PencilEdit01StrokeRounded
            : iconName === "pencil-edit-01" && iconVariant === "solid" ? SolidIcons.PencilEdit01SolidRounded
            : iconName === "pencil-edit-01" && iconVariant === "bulk" ? BulkIcons.PencilEdit01BulkRounded
            : iconName === "pencil-edit-01" && iconVariant === "twotone" ? TwotoneIcons.PencilEdit01TwotoneRounded
            : iconName === "pencil-edit-01" && iconVariant === "duotone" ? DuotoneIcons.PencilEdit01DuotoneRounded
        : iconName === "pencil-edit-02" && iconVariant === "stroke" ? StrokeIcons.PencilEdit02StrokeRounded
            : iconName === "pencil-edit-02" && iconVariant === "solid" ? SolidIcons.PencilEdit02SolidRounded
            : iconName === "pencil-edit-02" && iconVariant === "bulk" ? BulkIcons.PencilEdit02BulkRounded
            : iconName === "pencil-edit-02" && iconVariant === "twotone" ? TwotoneIcons.PencilEdit02TwotoneRounded
            : iconName === "pencil-edit-02" && iconVariant === "duotone" ? DuotoneIcons.PencilEdit02DuotoneRounded
        : iconName === "grid" && iconVariant === "stroke" ? StrokeIcons.GridStrokeRounded
            : iconName === "grid" && iconVariant === "solid" ? SolidIcons.GridSolidRounded
            : iconName === "grid" && iconVariant === "bulk" ? BulkIcons.GridBulkRounded
            : iconName === "grid" && iconVariant === "twotone" ? TwotoneIcons.GridTwotoneRounded
            : iconName === "grid" && iconVariant === "duotone" ? DuotoneIcons.GridDuotoneRounded
        : iconName === "link-04" && iconVariant === "stroke" ? StrokeIcons.Link04StrokeRounded
            : iconName === "link-04" && iconVariant === "solid" ? SolidIcons.Link04SolidRounded
            : iconName === "link-04" && iconVariant === "bulk" ? BulkIcons.Link04BulkRounded
            : iconName === "link-04" && iconVariant === "twotone" ? TwotoneIcons.Link04TwotoneRounded
            : iconName === "link-04" && iconVariant === "duotone" ? DuotoneIcons.Link04DuotoneRounded
        : iconName === "file-edit" && iconVariant === "stroke" ? StrokeIcons.FileEditStrokeRounded
            : iconName === "file-edit" && iconVariant === "solid" ? SolidIcons.FileEditSolidRounded
            : iconName === "file-edit" && iconVariant === "bulk" ? BulkIcons.FileEditBulkRounded
            : iconName === "file-edit" && iconVariant === "twotone" ? TwotoneIcons.FileEditTwotoneRounded
            : iconName === "file-edit" && iconVariant === "duotone" ? DuotoneIcons.FileEditDuotoneRounded
        : iconName === "alert-circle" && iconVariant === "stroke" ? StrokeIcons.AlertCircleStrokeRounded
            : iconName === "alert-circle" && iconVariant === "solid" ? SolidIcons.AlertCircleSolidRounded
            : iconName === "alert-circle" && iconVariant === "bulk" ? BulkIcons.AlertCircleBulkRounded
            : iconName === "alert-circle" && iconVariant === "twotone" ? TwotoneIcons.AlertCircleTwotoneRounded
            : iconName === "alert-circle" && iconVariant === "duotone" ? DuotoneIcons.AlertCircleDuotoneRounded
        : iconName === "checkmark-badge-03" && iconVariant === "stroke" ? StrokeIcons.CheckmarkBadge03StrokeRounded
            : iconName === "checkmark-badge-03" && iconVariant === "solid" ? SolidIcons.CheckmarkBadge03SolidRounded
            : iconName === "checkmark-badge-03" && iconVariant === "bulk" ? BulkIcons.CheckmarkBadge03BulkRounded
            : iconName === "checkmark-badge-03" && iconVariant === "twotone" ? TwotoneIcons.CheckmarkBadge03TwotoneRounded
            : iconName === "checkmark-badge-03" && iconVariant === "duotone" ? DuotoneIcons.CheckmarkBadge03DuotoneRounded
        : iconName === "cone-01" && iconVariant === "stroke" ? StrokeIcons.Cone01StrokeRounded
            : iconName === "cone-01" && iconVariant === "solid" ? SolidIcons.Cone01SolidRounded
            : iconName === "cone-01" && iconVariant === "bulk" ? BulkIcons.Cone01BulkRounded
            : iconName === "cone-01" && iconVariant === "twotone" ? TwotoneIcons.Cone01TwotoneRounded
            : iconName === "cone-01" && iconVariant === "duotone" ? DuotoneIcons.Cone01DuotoneRounded
        : iconName === "add-01" && iconVariant === "stroke" ? StrokeIcons.Add01StrokeRounded
            : iconName === "add-01" && iconVariant === "solid" ? SolidIcons.Add01SolidRounded
            : iconName === "add-01" && iconVariant === "bulk" ? BulkIcons.Add01BulkRounded
            : iconName === "add-01" && iconVariant === "twotone" ? TwotoneIcons.Add01TwotoneRounded
            : iconName === "add-01" && iconVariant === "duotone" ? DuotoneIcons.Add01DuotoneRounded
        : iconName === "alert-01" && iconVariant === "stroke" ? StrokeIcons.Alert01StrokeRounded
            : iconName === "alert-01" && iconVariant === "solid" ? SolidIcons.Alert01SolidRounded
            : iconName === "alert-01" && iconVariant === "bulk" ? BulkIcons.Alert01BulkRounded
            : iconName === "alert-01" && iconVariant === "twotone" ? TwotoneIcons.Alert01TwotoneRounded
            : iconName === "alert-01" && iconVariant === "duotone" ? DuotoneIcons.Alert01DuotoneRounded
        : iconName === "alert-02" && iconVariant === "stroke" ? StrokeIcons.Alert02StrokeRounded
            : iconName === "alert-02" && iconVariant === "solid" ? SolidIcons.Alert02SolidRounded
            : iconName === "alert-02" && iconVariant === "bulk" ? BulkIcons.Alert02BulkRounded
            : iconName === "alert-02" && iconVariant === "twotone" ? TwotoneIcons.Alert02TwotoneRounded
            : iconName === "alert-02" && iconVariant === "duotone" ? DuotoneIcons.Alert02DuotoneRounded
        : iconName === "archive-02" && iconVariant === "stroke" ? StrokeIcons.Archive02StrokeRounded
            : iconName === "archive-02" && iconVariant === "solid" ? SolidIcons.Archive02SolidRounded
            : iconName === "archive-02" && iconVariant === "bulk" ? BulkIcons.Archive02BulkRounded
            : iconName === "archive-02" && iconVariant === "twotone" ? TwotoneIcons.Archive02TwotoneRounded
            : iconName === "archive-02" && iconVariant === "duotone" ? DuotoneIcons.Archive02DuotoneRounded
        : iconName === "bookmark-01" && iconVariant === "stroke" ? StrokeIcons.Bookmark01StrokeRounded
            : iconName === "bookmark-01" && iconVariant === "solid" ? SolidIcons.Bookmark01SolidRounded
            : iconName === "bookmark-01" && iconVariant === "bulk" ? BulkIcons.Bookmark01BulkRounded
            : iconName === "bookmark-01" && iconVariant === "twotone" ? TwotoneIcons.Bookmark01TwotoneRounded
            : iconName === "bookmark-01" && iconVariant === "duotone" ? DuotoneIcons.Bookmark01DuotoneRounded
        : iconName === "cancel-circle" && iconVariant === "stroke" ? StrokeIcons.CancelCircleStrokeRounded
            : iconName === "cancel-circle" && iconVariant === "solid" ? SolidIcons.CancelCircleSolidRounded
            : iconName === "cancel-circle" && iconVariant === "bulk" ? BulkIcons.CancelCircleBulkRounded
            : iconName === "cancel-circle" && iconVariant === "twotone" ? TwotoneIcons.CancelCircleTwotoneRounded
            : iconName === "cancel-circle" && iconVariant === "duotone" ? DuotoneIcons.CancelCircleDuotoneRounded
        : iconName === "checkmark-circle-02" && iconVariant === "stroke" ? StrokeIcons.CheckmarkCircle02StrokeRounded
            : iconName === "checkmark-circle-02" && iconVariant === "solid" ? SolidIcons.CheckmarkCircle02SolidRounded
            : iconName === "checkmark-circle-02" && iconVariant === "bulk" ? BulkIcons.CheckmarkCircle02BulkRounded
            : iconName === "checkmark-circle-02" && iconVariant === "twotone" ? TwotoneIcons.CheckmarkCircle02TwotoneRounded
            : iconName === "checkmark-circle-02" && iconVariant === "duotone" ? DuotoneIcons.CheckmarkCircle02DuotoneRounded
        : iconName === "dashboard-browsing" && iconVariant === "stroke" ? StrokeIcons.DashboardBrowsingStrokeRounded
            : iconName === "dashboard-browsing" && iconVariant === "solid" ? SolidIcons.DashboardBrowsingSolidRounded
            : iconName === "dashboard-browsing" && iconVariant === "bulk" ? BulkIcons.DashboardBrowsingBulkRounded
            : iconName === "dashboard-browsing" && iconVariant === "twotone" ? TwotoneIcons.DashboardBrowsingTwotoneRounded
            : iconName === "dashboard-browsing" && iconVariant === "duotone" ? DuotoneIcons.DashboardBrowsingDuotoneRounded
        : iconName === "dashboard-speed-02" && iconVariant === "stroke" ? StrokeIcons.DashboardSpeed02StrokeRounded
            : iconName === "dashboard-speed-02" && iconVariant === "solid" ? SolidIcons.DashboardSpeed02SolidRounded
            : iconName === "dashboard-speed-02" && iconVariant === "bulk" ? BulkIcons.DashboardSpeed02BulkRounded
            : iconName === "dashboard-speed-02" && iconVariant === "twotone" ? TwotoneIcons.DashboardSpeed02TwotoneRounded
            : iconName === "dashboard-speed-02" && iconVariant === "duotone" ? DuotoneIcons.DashboardSpeed02DuotoneRounded
        : iconName === "favourite" && iconVariant === "stroke" ? StrokeIcons.FavouriteStrokeRounded
            : iconName === "favourite" && iconVariant === "solid" ? SolidIcons.FavouriteSolidRounded
            : iconName === "favourite" && iconVariant === "bulk" ? BulkIcons.FavouriteBulkRounded
            : iconName === "favourite" && iconVariant === "twotone" ? TwotoneIcons.FavouriteTwotoneRounded
            : iconName === "favourite" && iconVariant === "duotone" ? DuotoneIcons.FavouriteDuotoneRounded            
        : iconName === "flag-02" && iconVariant === "stroke" ? StrokeIcons.Flag02StrokeRounded
            : iconName === "flag-02" && iconVariant === "solid" ? SolidIcons.Flag02SolidRounded
            : iconName === "flag-02" && iconVariant === "bulk" ? BulkIcons.Flag02BulkRounded
            : iconName === "flag-02" && iconVariant === "twotone" ? TwotoneIcons.Flag02TwotoneRounded
            : iconName === "flag-02" && iconVariant === "duotone" ? DuotoneIcons.Flag02DuotoneRounded
        : iconName === "folder-01" && iconVariant === "stroke" ? StrokeIcons.Folder01StrokeRounded
            : iconName === "folder-01" && iconVariant === "solid" ? SolidIcons.Folder01SolidRounded
            : iconName === "folder-01" && iconVariant === "bulk" ? BulkIcons.Folder01BulkRounded
            : iconName === "folder-01" && iconVariant === "twotone" ? TwotoneIcons.Folder01TwotoneRounded
            : iconName === "folder-01" && iconVariant === "duotone" ? DuotoneIcons.Folder01DuotoneRounded
        : iconName === "laurel-wreath" && iconVariant === "stroke" ? StrokeIcons.LaurelWreath02StrokeRounded
            : iconName === "laurel-wreath" && iconVariant === "solid" ? SolidIcons.LaurelWreath02SolidRounded
            : iconName === "laurel-wreath" && iconVariant === "bulk" ? BulkIcons.LaurelWreath02BulkRounded
            : iconName === "laurel-wreath" && iconVariant === "twotone" ? TwotoneIcons.LaurelWreath02TwotoneRounded
            : iconName === "laurel-wreath" && iconVariant === "duotone" ? DuotoneIcons.LaurelWreath02DuotoneRounded
        : iconName === "location-01" && iconVariant === "stroke" ? StrokeIcons.Location01StrokeRounded
            : iconName === "location-01" && iconVariant === "solid" ? SolidIcons.Location01SolidRounded
            : iconName === "location-01" && iconVariant === "bulk" ? BulkIcons.Location01BulkRounded
            : iconName === "location-01" && iconVariant === "twotone" ? TwotoneIcons.Location01TwotoneRounded
            : iconName === "location-01" && iconVariant === "duotone" ? DuotoneIcons.Location01DuotoneRounded
        : iconName === "mail-01" && iconVariant === "stroke" ? StrokeIcons.Mail01StrokeRounded
            : iconName === "mail-01" && iconVariant === "solid" ? SolidIcons.Mail01SolidRounded
            : iconName === "mail-01" && iconVariant === "bulk" ? BulkIcons.Mail01BulkRounded
            : iconName === "mail-01" && iconVariant === "twotone" ? TwotoneIcons.Mail01TwotoneRounded
            : iconName === "mail-01" && iconVariant === "duotone" ? DuotoneIcons.Mail01DuotoneRounded
        : iconName === "notification-03" && iconVariant === "stroke" ? StrokeIcons.Notification03StrokeRounded
            : iconName === "notification-03" && iconVariant === "solid" ? SolidIcons.Notification03SolidRounded
            : iconName === "notification-03" && iconVariant === "bulk" ? BulkIcons.Notification03BulkRounded
            : iconName === "notification-03" && iconVariant === "twotone" ? TwotoneIcons.Notification03TwotoneRounded
            : iconName === "notification-03" && iconVariant === "duotone" ? DuotoneIcons.Notification03DuotoneRounded
        : iconName === "pencil" && iconVariant === "stroke" ? StrokeIcons.PencilStrokeRounded
            : iconName === "pencil" && iconVariant === "solid" ? SolidIcons.PencilSolidRounded
            : iconName === "pencil" && iconVariant === "bulk" ? BulkIcons.PencilBulkRounded
            : iconName === "pencil" && iconVariant === "twotone" ? TwotoneIcons.PencilTwotoneRounded
            : iconName === "pencil" && iconVariant === "duotone" ? DuotoneIcons.PencilDuotoneRounded
        : iconName === "search-01" && iconVariant === "stroke" ? StrokeIcons.Search01StrokeRounded
            : iconName === "search-01" && iconVariant === "solid" ? SolidIcons.Search01SolidRounded
            : iconName === "search-01" && iconVariant === "bulk" ? BulkIcons.Search01BulkRounded
            : iconName === "search-01" && iconVariant === "twotone" ? TwotoneIcons.Search01TwotoneRounded
            : iconName === "search-01" && iconVariant === "duotone" ? DuotoneIcons.Search01DuotoneRounded
        : iconName === "security-check" && iconVariant === "stroke" ? StrokeIcons.SecurityCheckStrokeRounded
            : iconName === "security-check" && iconVariant === "solid" ? SolidIcons.SecurityCheckSolidRounded
            : iconName === "security-check" && iconVariant === "bulk" ? BulkIcons.SecurityCheckBulkRounded
            : iconName === "security-check" && iconVariant === "twotone" ? TwotoneIcons.SecurityCheckTwotoneRounded
            : iconName === "security-check" && iconVariant === "duotone" ? DuotoneIcons.SecurityCheckDuotoneRounded
        : iconName === "sent" && iconVariant === "stroke" ? StrokeIcons.SentStrokeRounded
            : iconName === "sent" && iconVariant === "solid" ? SolidIcons.SentSolidRounded
            : iconName === "sent" && iconVariant === "bulk" ? BulkIcons.SentBulkRounded
            : iconName === "sent" && iconVariant === "twotone" ? TwotoneIcons.SentTwotoneRounded
            : iconName === "sent" && iconVariant === "duotone" ? DuotoneIcons.SentDuotoneRounded
        : iconName === "settings-02" && iconVariant === "stroke" ? StrokeIcons.Settings02StrokeRounded
            : iconName === "settings-02" && iconVariant === "solid" ? SolidIcons.Settings02SolidRounded
            : iconName === "settings-02" && iconVariant === "bulk" ? BulkIcons.Settings02BulkRounded
            : iconName === "settings-02" && iconVariant === "twotone" ? TwotoneIcons.Settings02TwotoneRounded
            : iconName === "settings-02" && iconVariant === "duotone" ? DuotoneIcons.Settings02DuotoneRounded
        : iconName === "star" && iconVariant === "stroke" ? StrokeIcons.StarStrokeRounded
            : iconName === "star" && iconVariant === "solid" ? SolidIcons.StarSolidRounded
            : iconName === "star" && iconVariant === "bulk" ? BulkIcons.StarBulkRounded
            : iconName === "star" && iconVariant === "twotone" ? TwotoneIcons.StarTwotoneRounded
            : iconName === "star" && iconVariant === "duotone" ? DuotoneIcons.StarDuotoneRounded
        : iconName === "tag-01" && iconVariant === "stroke" ? StrokeIcons.Tag01StrokeRounded
            : iconName === "tag-01" && iconVariant === "solid" ? SolidIcons.Tag01SolidRounded
            : iconName === "tag-01" && iconVariant === "bulk" ? BulkIcons.Tag01BulkRounded
            : iconName === "tag-01" && iconVariant === "twotone" ? TwotoneIcons.Tag01TwotoneRounded
            : iconName === "tag-01" && iconVariant === "duotone" ? DuotoneIcons.Tag01DuotoneRounded
        : iconName === "save-money-dollar" && iconVariant === "stroke" ? StrokeIcons.SaveMoneyDollarStrokeRounded
            : iconName === "save-money-dollar" && iconVariant === "solid" ? SolidIcons.SaveMoneyDollarSolidRounded
            : iconName === "save-money-dollar" && iconVariant === "bulk" ? BulkIcons.SaveMoneyDollarBulkRounded
            : iconName === "save-money-dollar" && iconVariant === "twotone" ? TwotoneIcons.SaveMoneyDollarTwotoneRounded
            : iconName === "save-money-dollar" && iconVariant === "duotone" ? DuotoneIcons.SaveMoneyDollarDuotoneRounded
        : iconName === "seo" && iconVariant === "stroke" ? StrokeIcons.SeoStrokeRounded
            : iconName === "seo" && iconVariant === "solid" ? SolidIcons.SeoSolidRounded
            : iconName === "seo" && iconVariant === "bulk" ? BulkIcons.SeoBulkRounded
            : iconName === "seo" && iconVariant === "twotone" ? TwotoneIcons.SeoTwotoneRounded
            : iconName === "seo" && iconVariant === "duotone" ? DuotoneIcons.SeoDuotoneRounded
        : iconName === "smart-phone-01" && iconVariant === "stroke" ? StrokeIcons.SmartPhone01StrokeRounded
            : iconName === "smart-phone-01" && iconVariant === "solid" ? SolidIcons.SmartPhone01SolidRounded
            : iconName === "smart-phone-01" && iconVariant === "bulk" ? BulkIcons.SmartPhone01BulkRounded
            : iconName === "smart-phone-01" && iconVariant === "twotone" ? TwotoneIcons.SmartPhone01TwotoneRounded
            : iconName === "smart-phone-01" && iconVariant === "duotone" ? DuotoneIcons.SmartPhone01DuotoneRounded
        : iconName === "text-font" && iconVariant === "stroke" ? StrokeIcons.TextFontStrokeRounded
            : iconName === "text-font" && iconVariant === "solid" ? SolidIcons.TextFontSolidRounded
            : iconName === "text-font" && iconVariant === "bulk" ? BulkIcons.TextFontBulkRounded
            : iconName === "text-font" && iconVariant === "twotone" ? TwotoneIcons.TextFontTwotoneRounded
            : iconName === "text-font" && iconVariant === "duotone" ? DuotoneIcons.TextFontDuotoneRounded
        : iconName === "new-twitter" && iconVariant === "stroke" ? StrokeIcons.NewTwitterStrokeRounded
            : iconName === "new-twitter" && iconVariant === "solid" ? SolidIcons.NewTwitterSolidRounded
            : iconName === "new-twitter" && iconVariant === "bulk" ? BulkIcons.NewTwitterBulkRounded
            : iconName === "new-twitter" && iconVariant === "twotone" ? TwotoneIcons.NewTwitterTwotoneRounded
            : iconName === "new-twitter" && iconVariant === "duotone" ? DuotoneIcons.NewTwitterDuotoneRounded
        : iconName === "game-controller-01" && iconVariant === "stroke" ? StrokeIcons.GameController01StrokeRounded
            : iconName === "game-controller-01" && iconVariant === "solid" ? SolidIcons.GameController01SolidRounded
            : iconName === "game-controller-01" && iconVariant === "bulk" ? BulkIcons.GameController01BulkRounded
            : iconName === "game-controller-01" && iconVariant === "twotone" ? TwotoneIcons.GameController01TwotoneRounded
            : iconName === "game-controller-01" && iconVariant === "duotone" ? DuotoneIcons.GameController01DuotoneRounded
        : iconName === "wifi-connected-02" && iconVariant === "stroke" ? StrokeIcons.WifiConnected02StrokeRounded
            : iconName === "wifi-connected-02" && iconVariant === "solid" ? SolidIcons.WifiConnected02SolidRounded
            : iconName === "wifi-connected-02" && iconVariant === "bulk" ? BulkIcons.WifiConnected02BulkRounded
            : iconName === "wifi-connected-02" && iconVariant === "twotone" ? TwotoneIcons.WifiConnected02TwotoneRounded
            : iconName === "wifi-connected-02" && iconVariant === "duotone" ? DuotoneIcons.WifiConnected02DuotoneRounded
        : iconName === "spotify" && iconVariant === "stroke" ? StrokeIcons.SpotifyStrokeRounded
            : iconName === "spotify" && iconVariant === "solid" ? SolidIcons.SpotifySolidRounded
            : iconName === "spotify" && iconVariant === "bulk" ? BulkIcons.SpotifyBulkRounded
            : iconName === "spotify" && iconVariant === "twotone" ? TwotoneIcons.SpotifyTwotoneRounded
            : iconName === "spotify" && iconVariant === "duotone" ? DuotoneIcons.SpotifyDuotoneRounded
        : iconName === "vimeo" && iconVariant === "stroke" ? StrokeIcons.VimeoStrokeRounded
            : iconName === "vimeo" && iconVariant === "solid" ? SolidIcons.VimeoSolidRounded
            : iconName === "vimeo" && iconVariant === "bulk" ? BulkIcons.VimeoBulkRounded
            : iconName === "vimeo" && iconVariant === "twotone" ? TwotoneIcons.VimeoTwotoneRounded
            : iconName === "vimeo" && iconVariant === "duotone" ? DuotoneIcons.VimeoDuotoneRounded
        : iconName === "music-note-square-02" && iconVariant === "stroke" ? StrokeIcons.MusicNoteSquare02StrokeRounded
            : iconName === "music-note-square-02" && iconVariant === "solid" ? SolidIcons.MusicNoteSquare02SolidRounded
            : iconName === "music-note-square-02" && iconVariant === "bulk" ? BulkIcons.MusicNoteSquare02BulkRounded
            : iconName === "music-note-square-02" && iconVariant === "twotone" ? TwotoneIcons.MusicNoteSquare02TwotoneRounded
            : iconName === "music-note-square-02" && iconVariant === "duotone" ? DuotoneIcons.MusicNoteSquare02DuotoneRounded
        : iconName === "shirt-01" && iconVariant === "stroke" ? StrokeIcons.Shirt01StrokeRounded
            : iconName === "shirt-01" && iconVariant === "solid" ? SolidIcons.Shirt01SolidRounded
            : iconName === "shirt-01" && iconVariant === "bulk" ? BulkIcons.Shirt01BulkRounded
            : iconName === "shirt-01" && iconVariant === "twotone" ? TwotoneIcons.Shirt01TwotoneRounded
            : iconName === "shirt-01" && iconVariant === "duotone" ? DuotoneIcons.Shirt01DuotoneRounded
        : iconName === "soundcloud" && iconVariant === "stroke" ? StrokeIcons.SoundcloudStrokeRounded
            : iconName === "soundcloud" && iconVariant === "solid" ? SolidIcons.SoundcloudSolidRounded
            : iconName === "soundcloud" && iconVariant === "bulk" ? BulkIcons.SoundcloudBulkRounded
            : iconName === "soundcloud" && iconVariant === "twotone" ? TwotoneIcons.SoundcloudTwotoneRounded
            : iconName === "soundcloud" && iconVariant === "duotone" ? DuotoneIcons.SoundcloudDuotoneRounded
        : iconName === "icon-jar" && iconVariant === "stroke" ? StrokeIcons.jarIconStrokeRounded
            : iconName === "icon-jar" && iconVariant === "solid" ? SolidIcons.jarIconSolidRounded
            : iconName === "icon-jar" && iconVariant === "bulk" ? BulkIcons.jarIconBulkRounded
            : iconName === "icon-jar" && iconVariant === "twotone" ? TwotoneIcons.jarIconTwotoneRounded
            : iconName === "icon-jar" && iconVariant === "duotone" ? DuotoneIcons.jarIconDuotoneRounded
        : iconName === "facebook-02" && iconVariant === "stroke" ? StrokeIcons.Facebook02StrokeRounded
            : iconName === "facebook-02" && iconVariant === "solid" ? SolidIcons.Facebook02SolidRounded
            : iconName === "facebook-02" && iconVariant === "bulk" ? BulkIcons.Facebook02BulkRounded
            : iconName === "facebook-02" && iconVariant === "twotone" ? TwotoneIcons.Facebook02TwotoneRounded
            : iconName === "facebook-02" && iconVariant === "duotone" ? DuotoneIcons.Facebook02DuotoneRounded
        : iconName === "github" && iconVariant === "stroke" ? StrokeIcons.GithubStrokeRounded
            : iconName === "github" && iconVariant === "solid" ? SolidIcons.GithubSolidRounded
            : iconName === "github" && iconVariant === "bulk" ? BulkIcons.GithubBulkRounded
            : iconName === "github" && iconVariant === "twotone" ? TwotoneIcons.GithubTwotoneRounded
            : iconName === "github" && iconVariant === "duotone" ? DuotoneIcons.GithubDuotoneRounded
        : iconName === "instagram" && iconVariant === "stroke" ? StrokeIcons.InstagramStrokeRounded
            : iconName === "instagram" && iconVariant === "solid" ? SolidIcons.InstagramSolidRounded
            : iconName === "instagram" && iconVariant === "bulk" ? BulkIcons.InstagramBulkRounded
            : iconName === "instagram" && iconVariant === "twotone" ? TwotoneIcons.InstagramTwotoneRounded
            : iconName === "instagram" && iconVariant === "duotone" ? DuotoneIcons.InstagramDuotoneRounded
        : iconName === "laptop-check" && iconVariant === "stroke" ? StrokeIcons.LaptopCheckStrokeRounded
            : iconName === "laptop-check" && iconVariant === "solid" ? SolidIcons.LaptopCheckSolidRounded
            : iconName === "laptop-check" && iconVariant === "bulk" ? BulkIcons.LaptopCheckBulkRounded
            : iconName === "laptop-check" && iconVariant === "twotone" ? TwotoneIcons.LaptopCheckTwotoneRounded
            : iconName === "laptop-check" && iconVariant === "duotone" ? DuotoneIcons.LaptopCheckDuotoneRounded
        : iconName === "linkedin-02" && iconVariant === "stroke" ? StrokeIcons.Linkedin02StrokeRounded
            : iconName === "linkedin-02" && iconVariant === "solid" ? SolidIcons.Linkedin02SolidRounded
            : iconName === "linkedin-02" && iconVariant === "bulk" ? BulkIcons.Linkedin02BulkRounded
            : iconName === "linkedin-02" && iconVariant === "twotone" ? TwotoneIcons.Linkedin02TwotoneRounded
            : iconName === "linkedin-02" && iconVariant === "duotone" ? DuotoneIcons.Linkedin02DuotoneRounded
        : iconName === "threads" && iconVariant === "stroke" ? StrokeIcons.ThreadsStrokeRounded
            : iconName === "threads" && iconVariant === "solid" ? SolidIcons.ThreadsSolidRounded
            : iconName === "threads" && iconVariant === "bulk" ? BulkIcons.ThreadsBulkRounded
            : iconName === "threads" && iconVariant === "twotone" ? TwotoneIcons.ThreadsTwotoneRounded
            : iconName === "threads" && iconVariant === "duotone" ? DuotoneIcons.ThreadsDuotoneRounded
        : iconName === "tiktok" && iconVariant === "stroke" ? StrokeIcons.TiktokStrokeRounded
            : iconName === "tiktok" && iconVariant === "solid" ? SolidIcons.TiktokSolidRounded
            : iconName === "tiktok" && iconVariant === "bulk" ? BulkIcons.TiktokBulkRounded
            : iconName === "tiktok" && iconVariant === "twotone" ? TwotoneIcons.TiktokTwotoneRounded
            : iconName === "tiktok" && iconVariant === "duotone" ? DuotoneIcons.TiktokDuotoneRounded
        : iconName === "property-edit" && iconVariant === "stroke" ? StrokeIcons.PropertyEditStrokeRounded
            : iconName === "property-edit" && iconVariant === "solid" ? SolidIcons.PropertyEditSolidRounded
            : iconName === "property-edit" && iconVariant === "bulk" ? BulkIcons.PropertyEditBulkRounded
            : iconName === "property-edit" && iconVariant === "twotone" ? TwotoneIcons.PropertyEditTwotoneRounded
            : iconName === "property-edit" && iconVariant === "duotone" ? DuotoneIcons.PropertyEditDuotoneRounded
        : iconName === "view" && iconVariant === "stroke" ? StrokeIcons.ViewStrokeRounded
            : iconName === "view" && iconVariant === "solid" ? SolidIcons.ViewSolidRounded
            : iconName === "view" && iconVariant === "bulk" ? BulkIcons.ViewBulkRounded
            : iconName === "view" && iconVariant === "twotone" ? TwotoneIcons.ViewTwotoneRounded
            : iconName === "view" && iconVariant === "duotone" ? DuotoneIcons.ViewDuotoneRounded
        : iconName === "arrow-left-02" && iconVariant === "stroke" ? StrokeIcons.ArrowLeft02StrokeRounded
            : iconName === "arrow-left-02" && iconVariant === "solid" ? SolidIcons.ArrowLeft02SolidRounded
            : iconName === "arrow-left-02" && iconVariant === "bulk" ? BulkIcons.ArrowLeft02BulkRounded
            : iconName === "arrow-left-02" && iconVariant === "twotone" ? TwotoneIcons.ArrowLeft02TwotoneRounded
            : iconName === "arrow-left-02" && iconVariant === "duotone" ? DuotoneIcons.ArrowLeft02DuotoneRounded
        : iconName === "arrow-left-03" && iconVariant === "stroke" ? StrokeIcons.ArrowLeft03StrokeRounded
            : iconName === "arrow-left-03" && iconVariant === "solid" ? SolidIcons.ArrowLeft03SolidRounded
            : iconName === "arrow-left-03" && iconVariant === "bulk" ? BulkIcons.ArrowLeft03BulkRounded
            : iconName === "arrow-left-03" && iconVariant === "twotone" ? TwotoneIcons.ArrowLeft03TwotoneRounded
            : iconName === "arrow-left-03" && iconVariant === "duotone" ? DuotoneIcons.ArrowLeft03DuotoneRounded
        : iconName === "arrow-right-01" && iconVariant === "stroke" ? StrokeIcons.ArrowRight01StrokeRounded
            : iconName === "arrow-right-01" && iconVariant === "solid" ? SolidIcons.ArrowRight01SolidRounded
            : iconName === "arrow-right-01" && iconVariant === "bulk" ? BulkIcons.ArrowRight01BulkRounded
            : iconName === "arrow-right-01" && iconVariant === "twotone" ? TwotoneIcons.ArrowRight01TwotoneRounded
            : iconName === "arrow-right-01" && iconVariant === "duotone" ? DuotoneIcons.ArrowRight01DuotoneRounded
        : iconName === "arrow-right-02" && iconVariant === "stroke" ? StrokeIcons.ArrowRight02StrokeRounded
            : iconName === "arrow-right-02" && iconVariant === "solid" ? SolidIcons.ArrowRight02SolidRounded
            : iconName === "arrow-right-02" && iconVariant === "bulk" ? BulkIcons.ArrowRight02BulkRounded
            : iconName === "arrow-right-02" && iconVariant === "twotone" ? TwotoneIcons.ArrowRight02TwotoneRounded
            : iconName === "arrow-right-02" && iconVariant === "duotone" ? DuotoneIcons.ArrowRight02DuotoneRounded
        : iconName === "arrow-right-03" && iconVariant === "stroke" ? StrokeIcons.ArrowRight03StrokeRounded
            : iconName === "arrow-right-03" && iconVariant === "solid" ? SolidIcons.ArrowRight03SolidRounded
            : iconName === "arrow-right-03" && iconVariant === "bulk" ? BulkIcons.ArrowRight03BulkRounded
            : iconName === "arrow-right-03" && iconVariant === "twotone" ? TwotoneIcons.ArrowRight03TwotoneRounded
            : iconName === "arrow-right-03" && iconVariant === "duotone" ? DuotoneIcons.ArrowRight03DuotoneRounded
        : iconName === "go-backward-10-sec" && iconVariant === "stroke" ? StrokeIcons.GoBackward10SecStrokeRounded
            : iconName === "go-backward-10-sec" && iconVariant === "solid" ? SolidIcons.GoBackward10SecSolidRounded
            : iconName === "go-backward-10-sec" && iconVariant === "bulk" ? BulkIcons.GoBackward10SecBulkRounded
            : iconName === "go-backward-10-sec" && iconVariant === "twotone" ? TwotoneIcons.GoBackward10SecTwotoneRounded
            : iconName === "go-backward-10-sec" && iconVariant === "duotone" ? DuotoneIcons.GoBackward10SecDuotoneRounded
        : iconName === "go-forward-10-sec" && iconVariant === "stroke" ? StrokeIcons.GoForward10SecStrokeRounded
            : iconName === "go-forward-10-sec" && iconVariant === "solid" ? SolidIcons.GoForward10SecSolidRounded
            : iconName === "go-forward-10-sec" && iconVariant === "bulk" ? BulkIcons.GoForward10SecBulkRounded
            : iconName === "go-forward-10-sec" && iconVariant === "twotone" ? TwotoneIcons.GoForward10SecTwotoneRounded
            : iconName === "go-forward-10-sec" && iconVariant === "duotone" ? DuotoneIcons.GoForward10SecDuotoneRounded
        : iconName === "pause" && iconVariant === "stroke" ? StrokeIcons.PauseStrokeRounded
            : iconName === "pause" && iconVariant === "solid" ? SolidIcons.PauseSolidRounded
            : iconName === "pause" && iconVariant === "bulk" ? BulkIcons.PauseBulkRounded
            : iconName === "pause" && iconVariant === "twotone" ? TwotoneIcons.PauseTwotoneRounded
            : iconName === "pause" && iconVariant === "duotone" ? DuotoneIcons.PauseDuotoneRounded
        : iconName === "loading-03" && iconVariant === "stroke" ? StrokeIcons.Loading03StrokeRounded
            : iconName === "loading-03" && iconVariant === "solid" ? SolidIcons.Loading03SolidRounded
            : iconName === "loading-03" && iconVariant === "bulk" ? BulkIcons.Loading03BulkRounded
            : iconName === "loading-03" && iconVariant === "twotone" ? TwotoneIcons.Loading03TwotoneRounded
            : iconName === "loading-03" && iconVariant === "duotone" ? DuotoneIcons.Loading03DuotoneRounded
        : iconName === "arrow-down-01" && iconVariant === "stroke" ? StrokeIcons.ArrowDown01StrokeRounded
            : iconName === "arrow-down-01" && iconVariant === "solid" ? SolidIcons.ArrowDown01SolidRounded
            : iconName === "arrow-down-01" && iconVariant === "bulk" ? BulkIcons.ArrowDown01BulkRounded
            : iconName === "arrow-down-01" && iconVariant === "twotone" ? TwotoneIcons.ArrowDown01TwotoneRounded
            : iconName === "arrow-down-01" && iconVariant === "duotone" ? DuotoneIcons.ArrowDown01DuotoneRounded
        : iconName === "briefcase-02" && iconVariant === "stroke" ? StrokeIcons.Briefcase02StrokeRounded
            : iconName === "briefcase-02" && iconVariant === "solid" ? SolidIcons.Briefcase02SolidRounded
            : iconName === "briefcase-02" && iconVariant === "bulk" ? BulkIcons.Briefcase02BulkRounded
            : iconName === "briefcase-02" && iconVariant === "twotone" ? TwotoneIcons.Briefcase02TwotoneRounded
            : iconName === "briefcase-02" && iconVariant === "duotone" ? DuotoneIcons.Briefcase02DuotoneRounded
        : iconName === "dashboard-square-02" && iconVariant === "stroke" ? StrokeIcons.DashboardSquare02StrokeRounded
            : iconName === "dashboard-square-02" && iconVariant === "solid" ? SolidIcons.DashboardSquare02SolidRounded
            : iconName === "dashboard-square-02" && iconVariant === "bulk" ? BulkIcons.DashboardSquare02BulkRounded
            : iconName === "dashboard-square-02" && iconVariant === "twotone" ? TwotoneIcons.DashboardSquare02TwotoneRounded
            : iconName === "dashboard-square-02" && iconVariant === "duotone" ? DuotoneIcons.DashboardSquare02DuotoneRounded
        : iconName === "job-search" && iconVariant === "stroke" ? StrokeIcons.JobSearchStrokeRounded
            : iconName === "job-search" && iconVariant === "solid" ? SolidIcons.JobSearchSolidRounded
            : iconName === "job-search" && iconVariant === "bulk" ? BulkIcons.JobSearchBulkRounded
            : iconName === "job-search" && iconVariant === "twotone" ? TwotoneIcons.JobSearchTwotoneRounded
            : iconName === "job-search" && iconVariant === "duotone" ? DuotoneIcons.JobSearchDuotoneRounded
        : iconName === "passport-01" && iconVariant === "stroke" ? StrokeIcons.Passport01StrokeRounded
            : iconName === "passport-01" && iconVariant === "solid" ? SolidIcons.Passport01SolidRounded
            : iconName === "passport-01" && iconVariant === "bulk" ? BulkIcons.Passport01BulkRounded
            : iconName === "passport-01" && iconVariant === "twotone" ? TwotoneIcons.Passport01TwotoneRounded
            : iconName === "passport-01" && iconVariant === "duotone" ? DuotoneIcons.Passport01DuotoneRounded
        : iconName === "passport" && iconVariant === "stroke" ? StrokeIcons.PassportStrokeRounded
            : iconName === "passport" && iconVariant === "solid" ? SolidIcons.PassportSolidRounded
            : iconName === "passport" && iconVariant === "bulk" ? BulkIcons.PassportBulkRounded
            : iconName === "passport" && iconVariant === "twotone" ? TwotoneIcons.PassportTwotoneRounded
            : iconName === "passport" && iconVariant === "duotone" ? DuotoneIcons.PassportDuotoneRounded
        : iconName === "hand-pointing-right-01" && iconVariant === "stroke" ? StrokeIcons.HandPointingRight01StrokeRounded
            : iconName === "hand-pointing-right-01" && iconVariant === "solid" ? SolidIcons.HandPointingRight01SolidRounded
            : iconName === "hand-pointing-right-01" && iconVariant === "bulk" ? BulkIcons.HandPointingRight01BulkRounded
            : iconName === "hand-pointing-right-01" && iconVariant === "twotone" ? TwotoneIcons.HandPointingRight01TwotoneRounded
            : iconName === "hand-pointing-right-01" && iconVariant === "duotone" ? DuotoneIcons.HandPointingRight01DuotoneRounded
        : iconName === "quote-down" && iconVariant === "stroke" ? StrokeIcons.QuoteDownStrokeRounded 
            : iconName === "quote-down" && iconVariant === "solid" ? SolidIcons.QuoteDownSolidRounded 
            : iconName === "quote-down" && iconVariant === "bulk" ? BulkIcons.QuoteDownBulkRounded 
            : iconName === "quote-down" && iconVariant === "twotone" ? TwotoneIcons.QuoteDownTwotoneRounded                
            : iconName === "quote-down" && iconVariant === "duotone" ? DuotoneIcons.QuoteDownDuotoneRounded 
        : iconName === "login-01" && iconVariant === "stroke" ? StrokeIcons.Login01StrokeRounded
            : iconName === "login-01" && iconVariant === "solid" ? SolidIcons.Login01SolidRounded
            : iconName === "login-01" && iconVariant === "bulk" ? BulkIcons.Login01BulkRounded
            : iconName === "login-01" && iconVariant === "twotone" ? TwotoneIcons.Login01TwotoneRounded
            : iconName === "login-01" && iconVariant === "duotone" ? DuotoneIcons.Login01DuotoneRounded
        : iconName === "twitter" && iconVariant === "stroke" ? StrokeIcons.TwitterStrokeRounded
            : iconName === "twitter" && iconVariant === "solid" ? SolidIcons.TwitterSolidRounded
            : iconName === "twitter" && iconVariant === "bulk" ? BulkIcons.TwitterBulkRounded
            : iconName === "twitter" && iconVariant === "twotone" ? TwotoneIcons.TwitterTwotoneRounded
            : iconName === "twitter" && iconVariant === "duotone" ? DuotoneIcons.TwitterDuotoneRounded
        : iconName === "files-01" && iconVariant === "stroke" ? StrokeIcons.Files01StrokeRounded
            : iconName === "files-01" && iconVariant === "solid" ? SolidIcons.Files01SolidRounded
            : iconName === "files-01" && iconVariant === "bulk" ? BulkIcons.Files01BulkRounded
            : iconName === "files-01" && iconVariant === "twotone" ? TwotoneIcons.Files01TwotoneRounded
            : iconName === "files-01" && iconVariant === "duotone" ? DuotoneIcons.Files01DuotoneRounded
        : iconName === "tick-01" && iconVariant === "stroke" ? StrokeIcons.Tick01StrokeRounded
            : iconName === "tick-01" && iconVariant === "solid" ? SolidIcons.Tick01SolidRounded
            : iconName === "tick-01" && iconVariant === "bulk" ? BulkIcons.Tick01BulkRounded
            : iconName === "tick-01" && iconVariant === "twotone" ? TwotoneIcons.Tick01TwotoneRounded
            : iconName === "tick-01" && iconVariant === "duotone" ? DuotoneIcons.Tick01DuotoneRounded
        : iconName === "ticket-01" && iconVariant === "stroke" ? StrokeIcons.Ticket01StrokeRounded
            : iconName === "ticket-01" && iconVariant === "solid" ? SolidIcons.Ticket01SolidRounded
            : iconName === "ticket-01" && iconVariant === "bulk" ? BulkIcons.Ticket01BulkRounded
            : iconName === "ticket-01" && iconVariant === "twotone" ? TwotoneIcons.Ticket01TwotoneRounded
            : iconName === "ticket-01" && iconVariant === "duotone" ? DuotoneIcons.Ticket01DuotoneRounded
        : iconName === "remove-01" && iconVariant === "stroke" ? StrokeIcons.Remove01StrokeRounded
            : iconName === "remove-01" && iconVariant === "solid" ? SolidIcons.Remove01SolidRounded
            : iconName === "remove-01" && iconVariant === "bulk" ? BulkIcons.Remove01BulkRounded
            : iconName === "remove-01" && iconVariant === "twotone" ? TwotoneIcons.Remove01TwotoneRounded
            : iconName === "remove-01" && iconVariant === "duotone" ? DuotoneIcons.Remove01DuotoneRounded
        : iconName === "book-02" && iconVariant === "stroke" ? StrokeIcons.Book02StrokeRounded
            : iconName === "book-02" && iconVariant === "solid" ? SolidIcons.Book02SolidRounded
            : iconName === "book-02" && iconVariant === "bulk" ? BulkIcons.Book02BulkRounded
            : iconName === "book-02" && iconVariant === "twotone" ? TwotoneIcons.Book02TwotoneRounded
            : iconName === "book-02" && iconVariant === "duotone" ? DuotoneIcons.Book02DuotoneRounded
        : iconName === "contact" && iconVariant === "stroke" ? StrokeIcons.ContactStrokeRounded
            : iconName === "contact" && iconVariant === "solid" ? SolidIcons.ContactSolidRounded
            : iconName === "contact" && iconVariant === "bulk" ? BulkIcons.ContactBulkRounded
            : iconName === "contact" && iconVariant === "twotone" ? TwotoneIcons.ContactTwotoneRounded
            : iconName === "contact" && iconVariant === "duotone" ? DuotoneIcons.ContactDuotoneRounded
        : iconName === "time-02" && iconVariant === "stroke" ? StrokeIcons.Time02StrokeRounded
            : iconName === "time-02" && iconVariant === "solid" ? SolidIcons.Time02SolidRounded
            : iconName === "time-02" && iconVariant === "bulk" ? BulkIcons.Time02BulkRounded
            : iconName === "time-02" && iconVariant === "twotone" ? TwotoneIcons.Time02TwotoneRounded
            : iconName === "time-02" && iconVariant === "duotone" ? DuotoneIcons.Time02DuotoneRounded
        : iconName === "license" && iconVariant === "stroke" ? StrokeIcons.LicenseStrokeRounded
            : iconName === "license" && iconVariant === "solid" ? SolidIcons.LicenseSolidRounded
            : iconName === "license" && iconVariant === "bulk" ? BulkIcons.LicenseBulkRounded
            : iconName === "license" && iconVariant === "twotone" ? TwotoneIcons.LicenseTwotoneRounded
            : iconName === "license" && iconVariant === "duotone" ? DuotoneIcons.LicenseDuotoneRounded
        : iconName === "task-add-01" && iconVariant === "stroke" ? StrokeIcons.TaskAdd01StrokeRounded
            : iconName === "task-add-01" && iconVariant === "solid" ? SolidIcons.TaskAdd01SolidRounded
            : iconName === "task-add-01" && iconVariant === "bulk" ? BulkIcons.TaskAdd01BulkRounded
            : iconName === "task-add-01" && iconVariant === "twotone" ? TwotoneIcons.TaskAdd01TwotoneRounded
            : iconName === "task-add-01" && iconVariant === "duotone" ? DuotoneIcons.TaskAdd01DuotoneRounded
        : iconName === "task-done-01" && iconVariant === "stroke" ? StrokeIcons.TaskDone01StrokeRounded
            : iconName === "task-done-01" && iconVariant === "solid" ? SolidIcons.TaskDone01SolidRounded
            : iconName === "task-done-01" && iconVariant === "bulk" ? BulkIcons.TaskDone01BulkRounded
            : iconName === "task-done-01" && iconVariant === "twotone" ? TwotoneIcons.TaskDone01TwotoneRounded
            : iconName === "task-done-01" && iconVariant === "duotone" ? DuotoneIcons.TaskDone01DuotoneRounded
        : iconName === "task-edit-01" && iconVariant === "stroke" ? StrokeIcons.TaskEdit01StrokeRounded
            : iconName === "task-edit-01" && iconVariant === "solid" ? SolidIcons.TaskEdit01SolidRounded
            : iconName === "task-edit-01" && iconVariant === "bulk" ? BulkIcons.TaskEdit01BulkRounded
            : iconName === "task-edit-01" && iconVariant === "twotone" ? TwotoneIcons.TaskEdit01TwotoneRounded
            : iconName === "task-edit-01" && iconVariant === "duotone" ? DuotoneIcons.TaskEdit01DuotoneRounded            
        : iconName === "arrow-down-02" && iconVariant === "stroke" ? StrokeIcons.ArrowDown02StrokeRounded
            : iconName === "arrow-down-02" && iconVariant === "solid" ? SolidIcons.ArrowDown02SolidRounded
            : iconName === "arrow-down-02" && iconVariant === "bulk" ? BulkIcons.ArrowDown02BulkRounded
            : iconName === "arrow-down-02" && iconVariant === "twotone" ? TwotoneIcons.ArrowDown02TwotoneRounded
            : iconName === "arrow-down-02" && iconVariant === "duotone" ? DuotoneIcons.ArrowDown02DuotoneRounded
        : iconName === "checkmark-badge-01" && iconVariant === "stroke" ? StrokeIcons.CheckmarkBadge01StrokeRounded
            : iconName === "checkmark-badge-01" && iconVariant === "solid" ? SolidIcons.CheckmarkBadge01SolidRounded
            : iconName === "checkmark-badge-01" && iconVariant === "bulk" ? BulkIcons.CheckmarkBadge01BulkRounded
            : iconName === "checkmark-badge-01" && iconVariant === "twotone" ? TwotoneIcons.CheckmarkBadge01TwotoneRounded
            : iconName === "checkmark-badge-01" && iconVariant === "duotone" ? DuotoneIcons.CheckmarkBadge01DuotoneRounded
        : iconName === "menu-01" && iconVariant === "stroke" ? StrokeIcons.Menu01StrokeRounded
            : iconName === "menu-01" && iconVariant === "solid" ? SolidIcons.Menu01SolidRounded
            : iconName === "menu-01" && iconVariant === "bulk" ? BulkIcons.Menu01BulkRounded
            : iconName === "menu-01" && iconVariant === "twotone" ? TwotoneIcons.Menu01TwotoneRounded
            : iconName === "menu-01" && iconVariant === "duotone" ? DuotoneIcons.Menu01DuotoneRounded
        : iconName === "remove-02" && iconVariant === "stroke" ? StrokeIcons.Remove02StrokeRounded
            : iconName === "remove-02" && iconVariant === "solid" ? SolidIcons.Remove02SolidRounded
            : iconName === "remove-02" && iconVariant === "bulk" ? BulkIcons.Remove02BulkRounded
            : iconName === "remove-02" && iconVariant === "twotone" ? TwotoneIcons.Remove02TwotoneRounded
            : iconName === "remove-02" && iconVariant === "duotone" ? DuotoneIcons.Remove02DuotoneRounded
        : iconName === "unavailable" && iconVariant === "stroke" ? StrokeIcons.UnavailableStrokeRounded
            : iconName === "unavailable" && iconVariant === "solid" ? SolidIcons.UnavailableSolidRounded
            : iconName === "unavailable" && iconVariant === "bulk" ? BulkIcons.UnavailableBulkRounded
            : iconName === "unavailable" && iconVariant === "twotone" ? TwotoneIcons.UnavailableTwotoneRounded
            : iconName === "unavailable" && iconVariant === "duotone" ? DuotoneIcons.UnavailableDuotoneRounded
        : iconName === "task-01" && iconVariant === "stroke" ? StrokeIcons.Task01StrokeRounded
            : iconName === "task-01" && iconVariant === "solid" ? SolidIcons.Task01SolidRounded
            : iconName === "task-01" && iconVariant === "bulk" ? BulkIcons.Task01BulkRounded
            : iconName === "task-01" && iconVariant === "twotone" ? TwotoneIcons.Task01TwotoneRounded
            : iconName === "task-01" && iconVariant === "duotone" ? DuotoneIcons.Task01DuotoneRounded
        : iconName === "user" && iconVariant === "stroke" ? StrokeIcons.UserStrokeRounded
            : iconName === "user" && iconVariant === "solid" ? SolidIcons.UserSolidRounded
            : iconName === "user" && iconVariant === "bulk" ? BulkIcons.UserBulkRounded
            : iconName === "user" && iconVariant === "twotone" ? TwotoneIcons.UserTwotoneRounded
            : iconName === "user" && iconVariant === "duotone" ? DuotoneIcons.UserDuotoneRounded
        : iconName === "user-shield-01" && iconVariant === "stroke" ? StrokeIcons.UserShield01StrokeRounded
            : iconName === "user-shield-01" && iconVariant === "solid" ? SolidIcons.UserShield01SolidRounded
            : iconName === "user-shield-01" && iconVariant === "bulk" ? BulkIcons.UserShield01BulkRounded
            : iconName === "user-shield-01" && iconVariant === "twotone" ? TwotoneIcons.UserShield01TwotoneRounded
            : iconName === "user-shield-01" && iconVariant === "duotone" ? DuotoneIcons.UserShield01DuotoneRounded
        : iconName === "album-01" && iconVariant === "stroke" ? StrokeIcons.Album01StrokeRounded
            : iconName === "album-01" && iconVariant === "solid" ? SolidIcons.Album01SolidRounded
            : iconName === "album-01" && iconVariant === "bulk" ? BulkIcons.Album01BulkRounded
            : iconName === "album-01" && iconVariant === "twotone" ? TwotoneIcons.Album01TwotoneRounded
            : iconName === "album-01" && iconVariant === "duotone" ? DuotoneIcons.Album01DuotoneRounded
        : iconName === "desk" && iconVariant === "stroke" ? StrokeIcons.DeskStrokeRounded
            : iconName === "desk" && iconVariant === "solid" ? SolidIcons.DeskSolidRounded
            : iconName === "desk" && iconVariant === "bulk" ? BulkIcons.DeskBulkRounded
            : iconName === "desk" && iconVariant === "twotone" ? TwotoneIcons.DeskTwotoneRounded
            : iconName === "desk" && iconVariant === "duotone" ? DuotoneIcons.DeskDuotoneRounded
        : iconName === "globe-02" && iconVariant === "stroke" ? StrokeIcons.Globe02StrokeRounded
            : iconName === "globe-02" && iconVariant === "solid" ? SolidIcons.Globe02SolidRounded
            : iconName === "globe-02" && iconVariant === "bulk" ? BulkIcons.Globe02BulkRounded
            : iconName === "globe-02" && iconVariant === "twotone" ? TwotoneIcons.Globe02TwotoneRounded
            : iconName === "globe-02" && iconVariant === "duotone" ? DuotoneIcons.Globe02DuotoneRounded
        : iconName === "pin-location-03" && iconVariant === "stroke" ? StrokeIcons.PinLocation03StrokeRounded
            : iconName === "pin-location-03" && iconVariant === "solid" ? SolidIcons.PinLocation03SolidRounded
            : iconName === "pin-location-03" && iconVariant === "bulk" ? BulkIcons.PinLocation03BulkRounded
            : iconName === "pin-location-03" && iconVariant === "twotone" ? TwotoneIcons.PinLocation03TwotoneRounded
            : iconName === "pin-location-03" && iconVariant === "duotone" ? DuotoneIcons.PinLocation03DuotoneRounded
        : iconName === "tags" && iconVariant === "stroke" ? StrokeIcons.TagsStrokeRounded
            : iconName === "tags" && iconVariant === "solid" ? SolidIcons.TagsSolidRounded
            : iconName === "tags" && iconVariant === "bulk" ? BulkIcons.TagsBulkRounded
            : iconName === "tags" && iconVariant === "twotone" ? TwotoneIcons.TagsTwotoneRounded
            : iconName === "tags" && iconVariant === "duotone" ? DuotoneIcons.TagsDuotoneRounded
        : iconName === "database-02" && iconVariant === "stroke" ? StrokeIcons.Database02StrokeRounded
            : iconName === "database-02" && iconVariant === "solid" ? SolidIcons.Database02SolidRounded
            : iconName === "database-02" && iconVariant === "bulk" ? BulkIcons.Database02BulkRounded
            : iconName === "database-02" && iconVariant === "twotone" ? TwotoneIcons.Database02TwotoneRounded
            : iconName === "database-02" && iconVariant === "duotone" ? DuotoneIcons.Database02DuotoneRounded
        : iconName === "library" && iconVariant === "stroke" ? StrokeIcons.LibraryStrokeRounded
            : iconName === "library" && iconVariant === "solid" ? SolidIcons.LibrarySolidRounded
            : iconName === "library" && iconVariant === "bulk" ? BulkIcons.LibraryBulkRounded
            : iconName === "library" && iconVariant === "twotone" ? TwotoneIcons.LibraryTwotoneRounded
            : iconName === "library" && iconVariant === "duotone" ? DuotoneIcons.LibraryDuotoneRounded
        : iconName === "user-multiple-02" && iconVariant === "stroke" ? StrokeIcons.UserMultiple02StrokeRounded
            : iconName === "user-multiple-02" && iconVariant === "solid" ? SolidIcons.UserMultiple02SolidRounded
            : iconName === "user-multiple-02" && iconVariant === "bulk" ? BulkIcons.UserMultiple02BulkRounded
            : iconName === "user-multiple-02" && iconVariant === "twotone" ? TwotoneIcons.UserMultiple02TwotoneRounded
            : iconName === "user-multiple-02" && iconVariant === "duotone" ? DuotoneIcons.UserMultiple02DuotoneRounded
        : iconName === "arrow-expand-01" && iconVariant === "stroke" ? StrokeIcons.ArrowExpand01StrokeRounded
            : iconName === "arrow-expand-01" && iconVariant === "solid" ? SolidIcons.ArrowExpand01SolidRounded
            : iconName === "arrow-expand-01" && iconVariant === "bulk" ? BulkIcons.ArrowExpand01BulkRounded
            : iconName === "arrow-expand-01" && iconVariant === "twotone" ? TwotoneIcons.ArrowExpand01TwotoneRounded
            : iconName === "arrow-expand-01" && iconVariant === "duotone" ? DuotoneIcons.ArrowExpand01DuotoneRounded
        : iconName === "arrow-expand" && iconVariant === "stroke" ? StrokeIcons.ArrowExpandStrokeRounded
            : iconName === "arrow-expand" && iconVariant === "solid" ? SolidIcons.ArrowExpandSolidRounded
            : iconName === "arrow-expand" && iconVariant === "bulk" ? BulkIcons.ArrowExpandBulkRounded
            : iconName === "arrow-expand" && iconVariant === "twotone" ? TwotoneIcons.ArrowExpandTwotoneRounded
            : iconName === "arrow-expand" && iconVariant === "duotone" ? DuotoneIcons.ArrowExpandDuotoneRounded
        : iconName === "arrow-horizontal" && iconVariant === "stroke" ? StrokeIcons.ArrowHorizontalStrokeRounded
            : iconName === "arrow-horizontal" && iconVariant === "solid" ? SolidIcons.ArrowHorizontalSolidRounded
            : iconName === "arrow-horizontal" && iconVariant === "bulk" ? BulkIcons.ArrowHorizontalBulkRounded
            : iconName === "arrow-horizontal" && iconVariant === "twotone" ? TwotoneIcons.ArrowHorizontalTwotoneRounded
            : iconName === "arrow-horizontal" && iconVariant === "duotone" ? DuotoneIcons.ArrowHorizontalDuotoneRounded
        : iconName === "arrow-left-01" && iconVariant === "stroke" ? StrokeIcons.ArrowLeft01StrokeRounded
            : iconName === "arrow-left-01" && iconVariant === "solid" ? SolidIcons.ArrowLeft01SolidRounded
            : iconName === "arrow-left-01" && iconVariant === "bulk" ? BulkIcons.ArrowLeft01BulkRounded
            : iconName === "arrow-left-01" && iconVariant === "twotone" ? TwotoneIcons.ArrowLeft01TwotoneRounded
            : iconName === "arrow-left-01" && iconVariant === "duotone" ? DuotoneIcons.ArrowLeft01DuotoneRounded
        : iconName === "arrow-shrink-01" && iconVariant === "stroke" ? StrokeIcons.ArrowShrink01StrokeRounded
            : iconName === "arrow-shrink-01" && iconVariant === "solid" ? SolidIcons.ArrowShrink01SolidRounded
            : iconName === "arrow-shrink-01" && iconVariant === "bulk" ? BulkIcons.ArrowShrink01BulkRounded
            : iconName === "arrow-shrink-01" && iconVariant === "twotone" ? TwotoneIcons.ArrowShrink01TwotoneRounded
            : iconName === "arrow-shrink-01" && iconVariant === "duotone" ? DuotoneIcons.ArrowShrink01DuotoneRounded
        : iconName === "arrow-shrink" && iconVariant === "stroke" ? StrokeIcons.ArrowShrinkStrokeRounded
            : iconName === "arrow-shrink" && iconVariant === "solid" ? SolidIcons.ArrowShrinkSolidRounded
            : iconName === "arrow-shrink" && iconVariant === "bulk" ? BulkIcons.ArrowShrinkBulkRounded
            : iconName === "arrow-shrink" && iconVariant === "twotone" ? TwotoneIcons.ArrowShrinkTwotoneRounded
            : iconName === "arrow-shrink" && iconVariant === "duotone" ? DuotoneIcons.ArrowShrinkDuotoneRounded
        : iconName === "arrow-up-right-02" && iconVariant === "stroke" ? StrokeIcons.ArrowUpRight02StrokeRounded
            : iconName === "arrow-up-right-02" && iconVariant === "solid" ? SolidIcons.ArrowUpRight02SolidRounded
            : iconName === "arrow-up-right-02" && iconVariant === "bulk" ? BulkIcons.ArrowUpRight02BulkRounded
            : iconName === "arrow-up-right-02" && iconVariant === "twotone" ? TwotoneIcons.ArrowUpRight02TwotoneRounded
            : iconName === "arrow-up-right-02" && iconVariant === "duotone" ? DuotoneIcons.ArrowUpRight02DuotoneRounded
        : iconName === "copy-01" && iconVariant === "stroke" ? StrokeIcons.Copy01StrokeRounded
            : iconName === "copy-01" && iconVariant === "solid" ? SolidIcons.Copy01SolidRounded
            : iconName === "copy-01" && iconVariant === "bulk" ? BulkIcons.Copy01BulkRounded
            : iconName === "copy-01" && iconVariant === "twotone" ? TwotoneIcons.Copy01TwotoneRounded
            : iconName === "copy-01" && iconVariant === "duotone" ? DuotoneIcons.Copy01DuotoneRounded
        : iconName === "database-01" && iconVariant === "stroke" ? StrokeIcons.Database01StrokeRounded
            : iconName === "database-01" && iconVariant === "solid" ? SolidIcons.Database01SolidRounded
            : iconName === "database-01" && iconVariant === "bulk" ? BulkIcons.Database01BulkRounded
            : iconName === "database-01" && iconVariant === "twotone" ? TwotoneIcons.Database01TwotoneRounded
            : iconName === "database-01" && iconVariant === "duotone" ? DuotoneIcons.Database01DuotoneRounded
        : iconName === "liver" && iconVariant === "stroke" ? StrokeIcons.LiverStrokeRounded
            : iconName === "liver" && iconVariant === "solid" ? SolidIcons.LiverSolidRounded
            : iconName === "liver" && iconVariant === "bulk" ? BulkIcons.LiverBulkRounded
            : iconName === "liver" && iconVariant === "twotone" ? TwotoneIcons.LiverTwotoneRounded
            : iconName === "liver" && iconVariant === "duotone" ? DuotoneIcons.LiverDuotoneRounded
        : iconName === "maximize-screen" && iconVariant === "stroke" ? StrokeIcons.MaximizeScreenStrokeRounded
            : iconName === "maximize-screen" && iconVariant === "solid" ? SolidIcons.MaximizeScreenSolidRounded
            : iconName === "maximize-screen" && iconVariant === "bulk" ? BulkIcons.MaximizeScreenBulkRounded
            : iconName === "maximize-screen" && iconVariant === "twotone" ? TwotoneIcons.MaximizeScreenTwotoneRounded
            : iconName === "maximize-screen" && iconVariant === "duotone" ? DuotoneIcons.MaximizeScreenDuotoneRounded
        : iconName === "minimize-screen" && iconVariant === "stroke" ? StrokeIcons.MinimizeScreenStrokeRounded
            : iconName === "minimize-screen" && iconVariant === "solid" ? SolidIcons.MinimizeScreenSolidRounded
            : iconName === "minimize-screen" && iconVariant === "bulk" ? BulkIcons.MinimizeScreenBulkRounded
            : iconName === "minimize-screen" && iconVariant === "twotone" ? TwotoneIcons.MinimizeScreenTwotoneRounded
            : iconName === "minimize-screen" && iconVariant === "duotone" ? DuotoneIcons.MinimizeScreenDuotoneRounded            
        : iconName === "share-05" && iconVariant === "stroke" ? StrokeIcons.Share05StrokeRounded
            : iconName === "share-05" && iconVariant === "solid" ? SolidIcons.Share05SolidRounded
            : iconName === "share-05" && iconVariant === "bulk" ? BulkIcons.Share05BulkRounded
            : iconName === "share-05" && iconVariant === "twotone" ? TwotoneIcons.Share05TwotoneRounded
            : iconName === "share-05" && iconVariant === "duotone" ? DuotoneIcons.Share05DuotoneRounded
        : iconName === "volume-mute-01" && iconVariant === "stroke" ? StrokeIcons.VolumeMute01StrokeRounded
            : iconName === "volume-mute-01" && iconVariant === "solid" ? SolidIcons.VolumeMute01SolidRounded
            : iconName === "volume-mute-01" && iconVariant === "bulk" ? BulkIcons.VolumeMute01BulkRounded
            : iconName === "volume-mute-01" && iconVariant === "twotone" ? TwotoneIcons.VolumeMute01TwotoneRounded
            : iconName === "volume-mute-01" && iconVariant === "duotone" ? DuotoneIcons.VolumeMute01DuotoneRounded
        : iconName === "volume-off" && iconVariant === "stroke" ? StrokeIcons.VolumeOffStrokeRounded
            : iconName === "volume-off" && iconVariant === "solid" ? SolidIcons.VolumeOffSolidRounded
            : iconName === "volume-off" && iconVariant === "bulk" ? BulkIcons.VolumeOffBulkRounded
            : iconName === "volume-off" && iconVariant === "twotone" ? TwotoneIcons.VolumeOffTwotoneRounded
            : iconName === "volume-off" && iconVariant === "duotone" ? DuotoneIcons.VolumeOffDuotoneRounded
        : iconName === "maps-search" && iconVariant === "stroke" ? StrokeIcons.MapsSearchStrokeRounded
            : iconName === "maps-search" && iconVariant === "solid" ? SolidIcons.MapsSearchSolidRounded
            : iconName === "maps-search" && iconVariant === "bulk" ? BulkIcons.MapsSearchBulkRounded
            : iconName === "maps-search" && iconVariant === "twotone" ? TwotoneIcons.MapsSearchTwotoneRounded
            : iconName === "maps-search" && iconVariant === "duotone" ? DuotoneIcons.MapsSearchDuotoneRounded
        : iconName === "camera-01" && iconVariant === "stroke" ? StrokeIcons.Camera01StrokeRounded
            : iconName === "camera-01" && iconVariant === "solid" ? SolidIcons.Camera01SolidRounded
            : iconName === "camera-01" && iconVariant === "bulk" ? BulkIcons.Camera01BulkRounded
            : iconName === "camera-01" && iconVariant === "twotone" ? TwotoneIcons.Camera01TwotoneRounded
            : iconName === "camera-01" && iconVariant === "duotone" ? DuotoneIcons.Camera01DuotoneRounded
        : iconName === "filter" && iconVariant === "stroke" ? StrokeIcons.FilterStrokeRounded
            : iconName === "filter" && iconVariant === "solid" ? SolidIcons.FilterSolidRounded
            : iconName === "filter" && iconVariant === "bulk" ? BulkIcons.FilterBulkRounded
            : iconName === "filter" && iconVariant === "twotone" ? TwotoneIcons.FilterTwotoneRounded
            : iconName === "filter" && iconVariant === "duotone" ? DuotoneIcons.FilterDuotoneRounded
        : iconName === "pin" && iconVariant === "stroke" ? StrokeIcons.PinStrokeRounded
            : iconName === "pin" && iconVariant === "solid" ? SolidIcons.PinSolidRounded
            : iconName === "pin" && iconVariant === "bulk" ? BulkIcons.PinBulkRounded
            : iconName === "pin" && iconVariant === "twotone" ? TwotoneIcons.PinTwotoneRounded
            : iconName === "pin" && iconVariant === "duotone" ? DuotoneIcons.PinDuotoneRounded
        : iconName === "sorting-19" && iconVariant === "stroke" ? StrokeIcons.Sorting19StrokeRounded
            : iconName === "sorting-19" && iconVariant === "solid" ? SolidIcons.Sorting19SolidRounded
            : iconName === "sorting-19" && iconVariant === "bulk" ? BulkIcons.Sorting19BulkRounded
            : iconName === "sorting-19" && iconVariant === "twotone" ? TwotoneIcons.Sorting19TwotoneRounded
            : iconName === "sorting-19" && iconVariant === "duotone" ? DuotoneIcons.Sorting19DuotoneRounded
        : iconName === "sorting-91" && iconVariant === "stroke" ? StrokeIcons.Sorting91StrokeRounded
            : iconName === "sorting-91" && iconVariant === "solid" ? SolidIcons.Sorting91SolidRounded
            : iconName === "sorting-91" && iconVariant === "bulk" ? BulkIcons.Sorting91BulkRounded
            : iconName === "sorting-91" && iconVariant === "twotone" ? TwotoneIcons.Sorting91TwotoneRounded
            : iconName === "sorting-91" && iconVariant === "duotone" ? DuotoneIcons.Sorting91DuotoneRounded
        : iconName === "music-note-01" && iconVariant === "stroke" ? StrokeIcons.MusicNote01StrokeRounded
            : iconName === "music-note-01" && iconVariant === "solid" ? SolidIcons.MusicNote01SolidRounded
            : iconName === "music-note-01" && iconVariant === "bulk" ? BulkIcons.MusicNote01BulkRounded
            : iconName === "music-note-01" && iconVariant === "twotone" ? TwotoneIcons.MusicNote01TwotoneRounded
            : iconName === "music-note-01" && iconVariant === "duotone" ? DuotoneIcons.MusicNote01DuotoneRounded
        : iconName === "delete-04" && iconVariant === "stroke" ? StrokeIcons.Delete04StrokeRounded
            : iconName === "delete-04" && iconVariant === "solid" ? SolidIcons.Delete04SolidRounded
            : iconName === "delete-04" && iconVariant === "bulk" ? BulkIcons.Delete04BulkRounded
            : iconName === "delete-04" && iconVariant === "twotone" ? TwotoneIcons.Delete04TwotoneRounded
            : iconName === "delete-04" && iconVariant === "duotone" ? DuotoneIcons.Delete04DuotoneRounded
        : iconName === "apple" && iconVariant === "stroke" ? StrokeIcons.AppleStrokeRounded
            : iconName === "apple" && iconVariant === "solid" ? SolidIcons.AppleSolidRounded
            : iconName === "apple" && iconVariant === "bulk" ? BulkIcons.AppleBulkRounded
            : iconName === "apple" && iconVariant === "twotone" ? TwotoneIcons.AppleTwotoneRounded
            : iconName === "apple" && iconVariant === "duotone" ? DuotoneIcons.AppleDuotoneRounded
        : iconName === "github-01" && iconVariant === "stroke" ? StrokeIcons.Github01StrokeRounded
            : iconName === "github-01" && iconVariant === "solid" ? SolidIcons.Github01SolidRounded
            : iconName === "github-01" && iconVariant === "bulk" ? BulkIcons.Github01BulkRounded
            : iconName === "github-01" && iconVariant === "twotone" ? TwotoneIcons.Github01TwotoneRounded
            : iconName === "github-01" && iconVariant === "duotone" ? DuotoneIcons.Github01DuotoneRounded
        : iconName === "message-download-01" && iconVariant === "stroke" ? StrokeIcons.MessageDownload01StrokeRounded
            : iconName === "message-download-01" && iconVariant === "solid" ? SolidIcons.MessageDownload01SolidRounded
            : iconName === "message-download-01" && iconVariant === "bulk" ? BulkIcons.MessageDownload01BulkRounded
            : iconName === "message-download-01" && iconVariant === "twotone" ? TwotoneIcons.MessageDownload01TwotoneRounded
            : iconName === "message-download-01" && iconVariant === "duotone" ? DuotoneIcons.MessageDownload01DuotoneRounded
        : iconName === "clipboard" && iconVariant === "stroke" ? StrokeIcons.ClipboardStrokeRounded
            : iconName === "clipboard" && iconVariant === "solid" ? SolidIcons.ClipboardSolidRounded
            : iconName === "clipboard" && iconVariant === "bulk" ? BulkIcons.ClipboardBulkRounded
            : iconName === "clipboard" && iconVariant === "twotone" ? TwotoneIcons.ClipboardTwotoneRounded
            : iconName === "clipboard" && iconVariant === "duotone" ? DuotoneIcons.ClipboardDuotoneRounded
        : iconName === "inbox" && iconVariant === "stroke" ? StrokeIcons.InboxStrokeRounded
            : iconName === "inbox" && iconVariant === "solid" ? SolidIcons.InboxSolidRounded
            : iconName === "inbox" && iconVariant === "bulk" ? BulkIcons.InboxBulkRounded
            : iconName === "inbox" && iconVariant === "twotone" ? TwotoneIcons.InboxTwotoneRounded
            : iconName === "inbox" && iconVariant === "duotone" ? DuotoneIcons.InboxDuotoneRounded
        : iconName === "document-validation" && iconVariant === "stroke" ? StrokeIcons.DocumentValidationStrokeRounded
            : iconName === "document-validation" && iconVariant === "solid" ? SolidIcons.DocumentValidationSolidRounded
            : iconName === "document-validation" && iconVariant === "bulk" ? BulkIcons.DocumentValidationBulkRounded
            : iconName === "document-validation" && iconVariant === "twotone" ? TwotoneIcons.DocumentValidationTwotoneRounded
            : iconName === "document-validation" && iconVariant === "duotone" ? DuotoneIcons.DocumentValidationDuotoneRounded
        : iconName === "loading-02" && iconVariant === "stroke" ? StrokeIcons.Loading02StrokeRounded
            : iconName === "loading-02" && iconVariant === "solid" ? SolidIcons.Loading02SolidRounded
            : iconName === "loading-02" && iconVariant === "bulk" ? BulkIcons.Loading02BulkRounded
            : iconName === "loading-02" && iconVariant === "twotone" ? TwotoneIcons.Loading02TwotoneRounded
            : iconName === "loading-02" && iconVariant === "duotone" ? DuotoneIcons.Loading02DuotoneRounded
        : iconName === "traffic-light" && iconVariant === "stroke" ? StrokeIcons.TrafficLightStrokeRounded
            : iconName === "traffic-light" && iconVariant === "solid" ? SolidIcons.TrafficLightSolidRounded
            : iconName === "traffic-light" && iconVariant === "bulk" ? BulkIcons.TrafficLightBulkRounded
            : iconName === "traffic-light" && iconVariant === "twotone" ? TwotoneIcons.TrafficLightTwotoneRounded
            : iconName === "traffic-light" && iconVariant === "duotone" ? DuotoneIcons.TrafficLightDuotoneRounded
        : iconName === "arrow-up-02" && iconVariant === "stroke" ? StrokeIcons.ArrowUp02StrokeRounded
            : iconName === "arrow-up-02" && iconVariant === "solid" ? SolidIcons.ArrowUp02SolidRounded
            : iconName === "arrow-up-02" && iconVariant === "bulk" ? BulkIcons.ArrowUp02BulkRounded
            : iconName === "arrow-up-02" && iconVariant === "twotone" ? TwotoneIcons.ArrowUp02TwotoneRounded
            : iconName === "arrow-up-02" && iconVariant === "duotone" ? DuotoneIcons.ArrowUp02DuotoneRounded
        : StrokeIcons.FileUnknownStrokeRounded

    return <HugeiconsIcon icon={getIcon} altIcon={getIcon} showAlt={altStatus} {...options} onClick={clickOption ? clickOption  : undefined} />
}