/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as PortfolioResumeRouteImport } from './routes/portfolio/resume'
import { Route as PortfolioPhotographyRouteImport } from './routes/portfolio/photography'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as LinkSetSlugRouteImport } from './routes/linkSet.$slug'
import { Route as FeedVideographyRouteImport } from './routes/feed/videography'
import { Route as FeedPhotographyRouteImport } from './routes/feed/photography'
import { Route as EmbedIdRouteImport } from './routes/embed.$id'
import { Route as BlogSearchRouteImport } from './routes/blog/search'
import { Route as AlbumSlugRouteImport } from './routes/album.$slug'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminResumeRouteImport } from './routes/_authed/admin/resume'
import { Route as AuthedAdminProfileRouteImport } from './routes/_authed/admin/profile'
import { Route as AuthedAdminPhotographyRouteImport } from './routes/_authed/admin/photography'
import { Route as AuthedAdminBlogRouteImport } from './routes/_authed/admin/blog'
import { Route as AuthedAdminAccountsRouteImport } from './routes/_authed/admin/accounts'
import { Route as AuthedAdminPhotoIdRouteImport } from './routes/_authed/admin/photo.$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioResumeRoute = PortfolioResumeRouteImport.update({
  id: '/portfolio/resume',
  path: '/portfolio/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioPhotographyRoute = PortfolioPhotographyRouteImport.update({
  id: '/portfolio/photography',
  path: '/portfolio/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkSetSlugRoute = LinkSetSlugRouteImport.update({
  id: '/linkSet/$slug',
  path: '/linkSet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedVideographyRoute = FeedVideographyRouteImport.update({
  id: '/feed/videography',
  path: '/feed/videography',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPhotographyRoute = FeedPhotographyRouteImport.update({
  id: '/feed/photography',
  path: '/feed/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedIdRoute = EmbedIdRouteImport.update({
  id: '/embed/$id',
  path: '/embed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSearchRoute = BlogSearchRouteImport.update({
  id: '/blog/search',
  path: '/blog/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumSlugRoute = AlbumSlugRouteImport.update({
  id: '/album/$slug',
  path: '/album/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminResumeRoute = AuthedAdminResumeRouteImport.update({
  id: '/admin/resume',
  path: '/admin/resume',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminProfileRoute = AuthedAdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPhotographyRoute = AuthedAdminPhotographyRouteImport.update({
  id: '/admin/photography',
  path: '/admin/photography',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminBlogRoute = AuthedAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAccountsRoute = AuthedAdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPhotoIdRoute = AuthedAdminPhotoIdRouteImport.update({
  id: '/admin/photo/$id',
  path: '/admin/photo/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/embed/$id': typeof EmbedIdRoute
  '/feed/photography': typeof FeedPhotographyRoute
  '/feed/videography': typeof FeedVideographyRoute
  '/linkSet/$slug': typeof LinkSetSlugRoute
  '/photo/$id': typeof PhotoIdRoute
  '/portfolio/photography': typeof PortfolioPhotographyRoute
  '/portfolio/resume': typeof PortfolioResumeRoute
  '/post/$slug': typeof PostSlugRoute
  '/video/$id': typeof VideoIdRoute
  '/blog/': typeof BlogIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/accounts': typeof AuthedAdminAccountsRoute
  '/admin/blog': typeof AuthedAdminBlogRoute
  '/admin/photography': typeof AuthedAdminPhotographyRoute
  '/admin/profile': typeof AuthedAdminProfileRoute
  '/admin/resume': typeof AuthedAdminResumeRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/photo/$id': typeof AuthedAdminPhotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/embed/$id': typeof EmbedIdRoute
  '/feed/photography': typeof FeedPhotographyRoute
  '/feed/videography': typeof FeedVideographyRoute
  '/linkSet/$slug': typeof LinkSetSlugRoute
  '/photo/$id': typeof PhotoIdRoute
  '/portfolio/photography': typeof PortfolioPhotographyRoute
  '/portfolio/resume': typeof PortfolioResumeRoute
  '/post/$slug': typeof PostSlugRoute
  '/video/$id': typeof VideoIdRoute
  '/blog': typeof BlogIndexRoute
  '/feed': typeof FeedIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/admin/accounts': typeof AuthedAdminAccountsRoute
  '/admin/blog': typeof AuthedAdminBlogRoute
  '/admin/photography': typeof AuthedAdminPhotographyRoute
  '/admin/profile': typeof AuthedAdminProfileRoute
  '/admin/resume': typeof AuthedAdminResumeRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/photo/$id': typeof AuthedAdminPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/embed/$id': typeof EmbedIdRoute
  '/feed/photography': typeof FeedPhotographyRoute
  '/feed/videography': typeof FeedVideographyRoute
  '/linkSet/$slug': typeof LinkSetSlugRoute
  '/photo/$id': typeof PhotoIdRoute
  '/portfolio/photography': typeof PortfolioPhotographyRoute
  '/portfolio/resume': typeof PortfolioResumeRoute
  '/post/$slug': typeof PostSlugRoute
  '/video/$id': typeof VideoIdRoute
  '/blog/': typeof BlogIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/_authed/admin/accounts': typeof AuthedAdminAccountsRoute
  '/_authed/admin/blog': typeof AuthedAdminBlogRoute
  '/_authed/admin/photography': typeof AuthedAdminPhotographyRoute
  '/_authed/admin/profile': typeof AuthedAdminProfileRoute
  '/_authed/admin/resume': typeof AuthedAdminResumeRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/photo/$id': typeof AuthedAdminPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/album/$slug'
    | '/blog/search'
    | '/embed/$id'
    | '/feed/photography'
    | '/feed/videography'
    | '/linkSet/$slug'
    | '/photo/$id'
    | '/portfolio/photography'
    | '/portfolio/resume'
    | '/post/$slug'
    | '/video/$id'
    | '/blog/'
    | '/feed/'
    | '/portfolio/'
    | '/admin/accounts'
    | '/admin/blog'
    | '/admin/photography'
    | '/admin/profile'
    | '/admin/resume'
    | '/admin/'
    | '/admin/photo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/album/$slug'
    | '/blog/search'
    | '/embed/$id'
    | '/feed/photography'
    | '/feed/videography'
    | '/linkSet/$slug'
    | '/photo/$id'
    | '/portfolio/photography'
    | '/portfolio/resume'
    | '/post/$slug'
    | '/video/$id'
    | '/blog'
    | '/feed'
    | '/portfolio'
    | '/admin/accounts'
    | '/admin/blog'
    | '/admin/photography'
    | '/admin/profile'
    | '/admin/resume'
    | '/admin'
    | '/admin/photo/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/contact'
    | '/album/$slug'
    | '/blog/search'
    | '/embed/$id'
    | '/feed/photography'
    | '/feed/videography'
    | '/linkSet/$slug'
    | '/photo/$id'
    | '/portfolio/photography'
    | '/portfolio/resume'
    | '/post/$slug'
    | '/video/$id'
    | '/blog/'
    | '/feed/'
    | '/portfolio/'
    | '/_authed/admin/accounts'
    | '/_authed/admin/blog'
    | '/_authed/admin/photography'
    | '/_authed/admin/profile'
    | '/_authed/admin/resume'
    | '/_authed/admin/'
    | '/_authed/admin/photo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  AlbumSlugRoute: typeof AlbumSlugRoute
  BlogSearchRoute: typeof BlogSearchRoute
  EmbedIdRoute: typeof EmbedIdRoute
  FeedPhotographyRoute: typeof FeedPhotographyRoute
  FeedVideographyRoute: typeof FeedVideographyRoute
  LinkSetSlugRoute: typeof LinkSetSlugRoute
  PhotoIdRoute: typeof PhotoIdRoute
  PortfolioPhotographyRoute: typeof PortfolioPhotographyRoute
  PortfolioResumeRoute: typeof PortfolioResumeRoute
  PostSlugRoute: typeof PostSlugRoute
  VideoIdRoute: typeof VideoIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/resume': {
      id: '/portfolio/resume'
      path: '/portfolio/resume'
      fullPath: '/portfolio/resume'
      preLoaderRoute: typeof PortfolioResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/photography': {
      id: '/portfolio/photography'
      path: '/portfolio/photography'
      fullPath: '/portfolio/photography'
      preLoaderRoute: typeof PortfolioPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkSet/$slug': {
      id: '/linkSet/$slug'
      path: '/linkSet/$slug'
      fullPath: '/linkSet/$slug'
      preLoaderRoute: typeof LinkSetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/videography': {
      id: '/feed/videography'
      path: '/feed/videography'
      fullPath: '/feed/videography'
      preLoaderRoute: typeof FeedVideographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/photography': {
      id: '/feed/photography'
      path: '/feed/photography'
      fullPath: '/feed/photography'
      preLoaderRoute: typeof FeedPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$id': {
      id: '/embed/$id'
      path: '/embed/$id'
      fullPath: '/embed/$id'
      preLoaderRoute: typeof EmbedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/search': {
      id: '/blog/search'
      path: '/blog/search'
      fullPath: '/blog/search'
      preLoaderRoute: typeof BlogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$slug': {
      id: '/album/$slug'
      path: '/album/$slug'
      fullPath: '/album/$slug'
      preLoaderRoute: typeof AlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/resume': {
      id: '/_authed/admin/resume'
      path: '/admin/resume'
      fullPath: '/admin/resume'
      preLoaderRoute: typeof AuthedAdminResumeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/profile': {
      id: '/_authed/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthedAdminProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/photography': {
      id: '/_authed/admin/photography'
      path: '/admin/photography'
      fullPath: '/admin/photography'
      preLoaderRoute: typeof AuthedAdminPhotographyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/blog': {
      id: '/_authed/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthedAdminBlogRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/accounts': {
      id: '/_authed/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthedAdminAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/photo/$id': {
      id: '/_authed/admin/photo/$id'
      path: '/admin/photo/$id'
      fullPath: '/admin/photo/$id'
      preLoaderRoute: typeof AuthedAdminPhotoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminAccountsRoute: typeof AuthedAdminAccountsRoute
  AuthedAdminBlogRoute: typeof AuthedAdminBlogRoute
  AuthedAdminPhotographyRoute: typeof AuthedAdminPhotographyRoute
  AuthedAdminProfileRoute: typeof AuthedAdminProfileRoute
  AuthedAdminResumeRoute: typeof AuthedAdminResumeRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminPhotoIdRoute: typeof AuthedAdminPhotoIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminAccountsRoute: AuthedAdminAccountsRoute,
  AuthedAdminBlogRoute: AuthedAdminBlogRoute,
  AuthedAdminPhotographyRoute: AuthedAdminPhotographyRoute,
  AuthedAdminProfileRoute: AuthedAdminProfileRoute,
  AuthedAdminResumeRoute: AuthedAdminResumeRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminPhotoIdRoute: AuthedAdminPhotoIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  AlbumSlugRoute: AlbumSlugRoute,
  BlogSearchRoute: BlogSearchRoute,
  EmbedIdRoute: EmbedIdRoute,
  FeedPhotographyRoute: FeedPhotographyRoute,
  FeedVideographyRoute: FeedVideographyRoute,
  LinkSetSlugRoute: LinkSetSlugRoute,
  PhotoIdRoute: PhotoIdRoute,
  PortfolioPhotographyRoute: PortfolioPhotographyRoute,
  PortfolioResumeRoute: PortfolioResumeRoute,
  PostSlugRoute: PostSlugRoute,
  VideoIdRoute: VideoIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
